"""
定数モジュール

GA固有定数、Enum、共通定数を提供します。
"""

from app.config.constants import SUPPORTED_TIMEFRAMES

from .common_constants import (
    AUTO_STRATEGY_DEFAULTS,
    COMPOSITE_INDICATORS,
    DATA_SOURCES,
    DEFAULT_STRATEGIES_LIMIT,
    DEFAULT_SYMBOL,
    GA_FALLBACK_END_DATE,
    GA_FALLBACK_START_DATE,
    MAX_STRATEGIES_LIMIT,
    MOVING_AVERAGE_INDICATORS,
    PREFERRED_MA_INDICATORS,
)
from .enums import (
    OPERATORS,
    EntryType,
    ExitType,
    IndicatorType,
    PositionSizingMethod,
    TPSLMethod,
)
from .ga_constants import (
    DEFAULT_FITNESS_CONSTRAINTS,
    DEFAULT_FITNESS_WEIGHTS,
    DEFAULT_GA_OBJECTIVE_WEIGHTS,
    DEFAULT_GA_OBJECTIVES,
    GA_DEFAULT_CONFIG,
    GA_DEFAULT_FITNESS_SHARING,
    GA_MUTATION_SETTINGS,
    GA_PARAMETER_RANGES,
)

__all__ = [
    # GA固有定数
    "GA_DEFAULT_CONFIG",
    "DEFAULT_FITNESS_WEIGHTS",
    "DEFAULT_FITNESS_CONSTRAINTS",
    "DEFAULT_GA_OBJECTIVES",
    "DEFAULT_GA_OBJECTIVE_WEIGHTS",
    "GA_DEFAULT_FITNESS_SHARING",
    "GA_PARAMETER_RANGES",
    "GA_MUTATION_SETTINGS",
    # Enum
    "PositionSizingMethod",
    "TPSLMethod",
    "EntryType",
    "ExitType",
    "IndicatorType",
    "OPERATORS",
    # 共通定数
    "DATA_SOURCES",
    "SUPPORTED_TIMEFRAMES",
    "DEFAULT_SYMBOL",
    "COMPOSITE_INDICATORS",
    "MOVING_AVERAGE_INDICATORS",
    "PREFERRED_MA_INDICATORS",
    "AUTO_STRATEGY_DEFAULTS",
    "DEFAULT_STRATEGIES_LIMIT",
    "MAX_STRATEGIES_LIMIT",
    "GA_FALLBACK_START_DATE",
    "GA_FALLBACK_END_DATE",
]
