from __future__ import annotations

from typing import Any, Dict

MANIFEST_MOMENTUM: Dict[str, Dict[str, Any]] = {
    "CCI": {
        "config": {
            "result_type": "single",
            "scale_type": "oscillator_plus_minus_100",
            "category": "momentum",
            "adapter_function": "app.services.indicators.technical_indicators.momentum.MomentumIndicators.cci",
            "required_data": ["high", "low", "close"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {"period": "length"},
            "parameters": {
                "period": {
                    "default_value": 14,
                    "min_value": 5,
                    "max_value": 50,
                    "description": "CCI計算期間",
                }
            },
            "pandas_function": None,
            "data_column": None,
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {"period": 14},
            "min_length_func": None,
            "absolute_min_length": 3,
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand} > {long_threshold}",
                "short": "{left_operand} < {short_threshold}",
            },
            "scale_type": "oscillator_plus_minus_100",
            "thresholds": {
                "aggressive": {"abs_limit": 100, "long_lt": -100},
                "conservative": {"abs_limit": 100, "long_lt": -100},
                "normal": {"abs_limit": 100, "long_lt": -100},
            },
            "type": "momentum",
        },
    },
    "CMO": {
        "config": {
            "result_type": "single",
            "scale_type": "oscillator_plus_minus_100",
            "category": "momentum",
            "adapter_function": "app.services.indicators.technical_indicators.momentum.MomentumIndicators.cmo",
            "required_data": ["close"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {"close": "data", "length": "length"},
            "parameters": {
                "length": {
                    "default_value": 14,
                    "min_value": 2,
                    "max_value": 100,
                    "description": "CMO計算期間",
                }
            },
            "pandas_function": "cmo",
            "data_column": "Close",
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {"length": 14},
            "min_length_func": None,
            "absolute_min_length": 3,
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand} > {threshold}",
                "short": "{left_operand} < {threshold}",
            },
            "scale_type": "oscillator_plus_minus_100",
            "thresholds": {"all": {"long_gt": 50, "short_lt": -50}},
            "type": "momentum",
        },
    },
    "FISHER": {
        "config": {
            "result_type": "complex",
            "scale_type": "momentum_zero_centered",
            "category": "momentum",
            "adapter_function": "app.services.indicators.technical_indicators.momentum.MomentumIndicators.fisher",
            "required_data": ["high", "low"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {
                "high": "high",
                "low": "low",
                "length": "length",
                "signal": "signal",
            },
            "parameters": {
                "length": {
                    "default_value": 9,
                    "min_value": 2,
                    "max_value": 100,
                    "description": "Fisher期間",
                },
                "signal": {
                    "default_value": 1,
                    "min_value": 1,
                    "max_value": 20,
                    "description": "シグナル期間",
                },
            },
            "pandas_function": "fisher",
            "data_column": None,
            "data_columns": ["High", "Low"],
            "returns": "multiple",
            "return_cols": ["FISHERT", "FISHERTs"],
            "multi_column": True,
            "default_values": {"length": 9, "signal": 1},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand}_0 > 0",
                "short": "{left_operand}_0 < 0",
            },
            "scale_type": "momentum_zero_centered",
            "thresholds": {"zero_cross": True},
            "type": "momentum",
        },
    },
    "KST": {
        "config": {
            "result_type": "complex",
            "scale_type": "momentum_zero_centered",
            "category": "momentum",
            "adapter_function": "app.services.indicators.technical_indicators.momentum.MomentumIndicators.kst",
            "required_data": ["close"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {
                "close": "data",
                "roc1": "roc1",
                "roc2": "roc2",
                "roc3": "roc3",
                "roc4": "roc4",
                "sma1": "sma1",
                "sma2": "sma2",
                "sma3": "sma3",
                "sma4": "sma4",
                "signal": "signal",
            },
            "parameters": {
                "roc1": {
                    "default_value": 10,
                    "min_value": 2,
                    "max_value": 60,
                    "description": "ROC1期間",
                },
                "roc2": {
                    "default_value": 15,
                    "min_value": 2,
                    "max_value": 60,
                    "description": "ROC2期間",
                },
                "roc3": {
                    "default_value": 20,
                    "min_value": 2,
                    "max_value": 60,
                    "description": "ROC3期間",
                },
                "roc4": {
                    "default_value": 30,
                    "min_value": 2,
                    "max_value": 90,
                    "description": "ROC4期間",
                },
                "sma1": {
                    "default_value": 10,
                    "min_value": 2,
                    "max_value": 60,
                    "description": "SMA1期間",
                },
                "sma2": {
                    "default_value": 10,
                    "min_value": 2,
                    "max_value": 60,
                    "description": "SMA2期間",
                },
                "sma3": {
                    "default_value": 10,
                    "min_value": 2,
                    "max_value": 60,
                    "description": "SMA3期間",
                },
                "sma4": {
                    "default_value": 15,
                    "min_value": 2,
                    "max_value": 90,
                    "description": "SMA4期間",
                },
                "signal": {
                    "default_value": 9,
                    "min_value": 1,
                    "max_value": 50,
                    "description": "シグナル期間",
                },
            },
            "pandas_function": "kst",
            "data_column": "Close",
            "data_columns": None,
            "returns": "multiple",
            "return_cols": ["KST", "KSTs"],
            "multi_column": False,
            "default_values": {
                "roc1": 10,
                "roc2": 15,
                "roc3": 20,
                "roc4": 30,
                "sma1": 10,
                "sma2": 10,
                "sma3": 10,
                "sma4": 15,
                "signal": 9,
            },
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand}_0 > 0",
                "short": "{left_operand}_0 < 0",
            },
            "scale_type": "momentum_zero_centered",
            "thresholds": {"zero_cross": True},
            "type": "momentum",
        },
    },
    "MACD": {
        "config": {
            "result_type": "complex",
            "scale_type": "momentum_zero_centered",
            "category": "momentum",
            "adapter_function": "app.services.indicators.technical_indicators.momentum.MomentumIndicators.macd",
            "required_data": ["close"],
            "output_names": ["MACD_0", "MACD_1", "MACD_2"],
            "default_output": "MACD_0",
            "aliases": None,
            "param_map": {
                "close": "data",
                "fast": "fast",
                "slow": "slow",
                "signal": "signal",
            },
            "parameters": {
                "fast": {
                    "default_value": 12,
                    "min_value": 2,
                    "max_value": 100,
                    "description": "高速移動平均期間",
                },
                "slow": {
                    "default_value": 26,
                    "min_value": 5,
                    "max_value": 200,
                    "description": "低速移動平均期間",
                },
                "signal": {
                    "default_value": 9,
                    "min_value": 2,
                    "max_value": 50,
                    "description": "シグナル線期間",
                },
            },
            "pandas_function": "macd",
            "data_column": "Close",
            "data_columns": None,
            "returns": "multiple",
            "return_cols": ["MACD", "Signal", "Histogram"],
            "multi_column": False,
            "default_values": {"fast": 12, "slow": 26, "signal": 9},
            "min_length_func": "MACD",
            "absolute_min_length": 38,
            # パラメータ依存関係制約: fast期間 < slow期間
            "parameter_constraints": [
                {"type": "less_than", "param1": "fast", "param2": "slow"},
            ],
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand}_0 > 0",
                "short": "{left_operand}_0 < 0",
            },
            "scale_type": "momentum_zero_centered",
            "thresholds": {"zero_cross": True},
            "type": "momentum",
        },
    },
    "PPO": {
        "config": {
            "result_type": "complex",
            "scale_type": "momentum_zero_centered",
            "category": "momentum",
            "adapter_function": "app.services.indicators.technical_indicators.momentum.MomentumIndicators.ppo",
            "required_data": ["close"],
            "output_names": ["PPO_0", "PPO_1", "PPO_2"],
            "default_output": "PPO_0",
            "aliases": None,
            "param_map": {
                "close": "data",
                "fast": "fast",
                "slow": "slow",
                "signal": "signal",
            },
            "parameters": {
                "fast": {
                    "default_value": 12,
                    "min_value": 2,
                    "max_value": 100,
                    "description": "高速移動平均期間",
                },
                "slow": {
                    "default_value": 26,
                    "min_value": 5,
                    "max_value": 200,
                    "description": "低速移動平均期間",
                },
                "signal": {
                    "default_value": 9,
                    "min_value": 2,
                    "max_value": 50,
                    "description": "シグナル線期間",
                },
            },
            "pandas_function": "ppo",
            "data_column": "Close",
            "data_columns": None,
            "returns": "multiple",
            "return_cols": ["PPO", "PPOs", "PPOh"],
            "multi_column": False,
            "default_values": {"fast": 12, "slow": 26, "signal": 9},
            "min_length_func": None,
            # パラメータ依存関係制約: fast期間 < slow期間
            "parameter_constraints": [
                {"type": "less_than", "param1": "fast", "param2": "slow"},
            ],
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand}_0 > 0",
                "short": "{left_operand}_0 < 0",
            },
            "scale_type": "momentum_zero_centered",
            "thresholds": {"zero_cross": True},
            "type": "momentum",
        },
    },
    "MOM": {
        "config": {
            "result_type": "single",
            "scale_type": "momentum_zero_centered",
            "category": "momentum",
            "adapter_function": "app.services.indicators.technical_indicators.momentum.MomentumIndicators.mom",
            "required_data": ["close"],
            "output_names": None,
            "default_output": None,
            "aliases": ["MOMENTUM"],
            "param_map": {"close": "data", "period": "length", "length": "length"},
            "parameters": {
                "period": {
                    "default_value": 10,
                    "min_value": 2,
                    "max_value": 50,
                    "description": "モメンタム計算期間",
                }
            },
            "pandas_function": None,
            "data_column": None,
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {"period": 10},
            "min_length_func": None,
            "absolute_min_length": 2,
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand} > {threshold}",
                "short": "{left_operand} < {threshold}",
            },
            "scale_type": "momentum_zero_centered",
            "thresholds": {
                "aggressive": {"long_lt": -10, "short_gt": 10},
                "conservative": {"long_lt": -2, "short_gt": 2},
                "normal": {"long_lt": -5, "short_gt": 5},
            },
            "type": "momentum",
        },
    },
    "QQE": {
        "config": {
            "result_type": "single",
            "scale_type": "oscillator_0_100",
            "category": "momentum",
            "adapter_function": "app.services.indicators.technical_indicators.momentum.MomentumIndicators.qqe",
            "required_data": ["close"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {"close": "data", "length": "length", "smooth": "smooth"},
            "parameters": {
                "length": {
                    "default_value": 14,
                    "min_value": 2,
                    "max_value": 200,
                    "description": "QQE計算期間",
                },
                "smooth": {
                    "default_value": 5,
                    "min_value": 1,
                    "max_value": 50,
                    "description": "QQE平滑化期間",
                },
            },
            "pandas_function": "qqe",
            "data_column": "Close",
            "data_columns": None,
            "returns": "multiple",
            "return_cols": ["QQE", "QQE_SIGNAL"],
            "multi_column": False,
            "default_values": {"length": 14, "smooth": 5},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand} < {threshold}",
                "short": "{left_operand} > {threshold}",
            },
            "scale_type": "oscillator_0_100",
            "thresholds": {
                "aggressive": {"long_lt": 15, "short_gt": 85},
                "conservative": {"long_lt": 25, "short_gt": 75},
                "normal": {"long_lt": 20, "short_gt": 80},
            },
            "type": "momentum",
        },
    },
    "ROC": {
        "config": {
            "result_type": "single",
            "scale_type": "momentum_zero_centered",
            "category": "momentum",
            "adapter_function": "app.services.indicators.technical_indicators.momentum.MomentumIndicators.roc",
            "required_data": ["close"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {"close": "data", "length": "length"},
            "parameters": {
                "length": {
                    "default_value": 10,
                    "min_value": 1,
                    "max_value": 100,
                    "description": "ROC計算期間",
                }
            },
            "pandas_function": None,
            "data_column": None,
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {"length": 10},
            "min_length_func": None,
            "absolute_min_length": 2,
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand} < {threshold}",
                "short": "{left_operand} > {threshold}",
            },
            "scale_type": "momentum_zero_centered",
            "thresholds": {
                "aggressive": {"long_lt": -3.0, "short_gt": 3.0},
                "combo": {
                    "condition": "abs_value >= primary or abs_value <= -secondary",
                    "primary": -5.0,
                    "secondary": 5.0,
                },
                "conservative": {"long_lt": -0.5, "short_gt": 0.5},
                "normal": {"long_lt": -1.5, "short_gt": 1.5},
                "range": {
                    "long_gt": -2.0,
                    "long_lt": 0.0,
                    "short_gt": 0.0,
                    "short_lt": 2.0,
                },
            },
            "type": "momentum",
        },
    },
    "CTI": {
        "config": {
            "result_type": "single",
            "scale_type": "momentum_zero_centered",
            "category": "momentum",
            "adapter_function": "app.services.indicators.technical_indicators.momentum.MomentumIndicators.cti",
            "required_data": ["close"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {"close": "data", "length": "length"},
            "parameters": {
                "length": {
                    "default_value": 12,
                    "min_value": 2,
                    "max_value": 200,
                    "description": "CTI計算期間",
                }
            },
            "pandas_function": "cti",
            "data_column": "Close",
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {"length": 12},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {"long": "{left_operand} > 0", "short": "{left_operand} < 0"},
            "scale_type": "momentum_zero_centered",
            "thresholds": {"zero_cross": True},
            "type": "momentum",
        },
    },
    "RSI": {
        "config": {
            "result_type": "single",
            "scale_type": "oscillator_0_100",
            "category": "momentum",
            "adapter_function": "app.services.indicators.technical_indicators.momentum.MomentumIndicators.rsi",
            "required_data": ["close"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {"close": "data", "length": "length"},
            "parameters": {
                "length": {
                    "default_value": 14,
                    "min_value": 2,
                    "max_value": 100,
                    "description": "RSI計算期間",
                }
            },
            "pandas_function": "rsi",
            "data_column": "Close",
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {"length": 14},
            "min_length_func": "RSI",
            "absolute_min_length": 3,
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand} > {threshold}",
                "short": "{left_operand} < {threshold}",
            },
            "scale_type": "oscillator_0_100",
            "thresholds": {
                "aggressive": {"long_gt": 70, "short_lt": 30},
                "conservative": {"long_gt": 80, "short_lt": 20},
                "normal": {"long_gt": 75, "short_lt": 25},
            },
            "type": "momentum",
        },
    },
    "SQUEEZE": {
        "config": {
            "result_type": "single",
            "scale_type": "oscillator_0_100",
            "category": "momentum",
            "adapter_function": "app.services.indicators.technical_indicators.momentum.MomentumIndicators.squeeze",
            "required_data": ["high", "low", "close"],
            "output_names": ["SQZ"],
            "default_output": "SQZ",
            "aliases": ["SQUEEZE"],
            "param_map": {
                "bb_length": "bb_length",
                "bb_std": "bb_std",
                "kc_length": "kc_length",
                "kc_scalar": "kc_scalar",
                "mom_length": "mom_length",
                "mom_smooth": "mom_smooth",
                "use_tr": "use_tr",
            },
            "parameters": {
                "bb_length": {
                    "default_value": 20,
                    "min_value": 5,
                    "max_value": 100,
                    "description": "Bollinger Bands length",
                },
                "bb_std": {
                    "default_value": 2.0,
                    "min_value": 0.5,
                    "max_value": 5.0,
                    "description": "Bollinger Bands standard deviation",
                },
                "kc_length": {
                    "default_value": 20,
                    "min_value": 5,
                    "max_value": 100,
                    "description": "Keltner Channels length",
                },
                "kc_scalar": {
                    "default_value": 1.5,
                    "min_value": 0.1,
                    "max_value": 5.0,
                    "description": "Keltner Channels scalar",
                },
                "mom_length": {
                    "default_value": 12,
                    "min_value": 2,
                    "max_value": 50,
                    "description": "Momentum length",
                },
                "mom_smooth": {
                    "default_value": 6,
                    "min_value": 1,
                    "max_value": 20,
                    "description": "Momentum smoothing",
                },
                "use_tr": {
                    "default_value": True,
                    "min_value": None,
                    "max_value": None,
                    "description": "Use True Range for calculations",
                },
            },
            "pandas_function": None,
            "data_column": None,
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {
                "bb_length": 20,
                "bb_std": 2.0,
                "kc_length": 20,
                "kc_scalar": 1.5,
                "mom_length": 12,
                "mom_smooth": 6,
                "use_tr": True,
            },
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand} < {threshold}",
                "short": "{left_operand} > {threshold}",
            },
            "scale_type": "oscillator_0_100",
            "thresholds": {
                "aggressive": {"long_lt": 15, "short_gt": 85},
                "normal": {"long_lt": 20, "short_gt": 80},
                "conservative": {"long_lt": 25, "short_gt": 75},
            },
            "type": "momentum",
        },
    },
    "STOCH": {
        "config": {
            "result_type": "complex",
            "scale_type": "oscillator_0_100",
            "category": "momentum",
            "adapter_function": "app.services.indicators.technical_indicators.momentum.MomentumIndicators.stoch",
            "required_data": ["high", "low", "close"],
            "output_names": ["STOCH_0", "STOCH_1"],
            "default_output": "STOCH_0",
            "aliases": ["STOCH"],
            "param_map": {
                "high": "high",
                "low": "low",
                "close": "close",
                "k_length": "k",
                "smooth_k": "smooth_k",
                "d_length": "d",
            },
            "parameters": {
                "k_length": {
                    "default_value": 14,
                    "min_value": 1,
                    "max_value": 30,
                    "description": "K期間",
                },
                "smooth_k": {
                    "default_value": 3,
                    "min_value": 1,
                    "max_value": 10,
                    "description": "K平滑化期間",
                },
                "d_length": {
                    "default_value": 3,
                    "min_value": 1,
                    "max_value": 10,
                    "description": "D期間",
                },
            },
            "pandas_function": "stoch",
            "data_column": None,
            "data_columns": ["High", "Low", "Close"],
            "returns": "multiple",
            "return_cols": ["STOCHk", "STOCHd"],
            "multi_column": True,
            "default_values": {"k_length": 14, "smooth_k": 3, "d_length": 3},
            "min_length_func": "STOCH",
            "absolute_min_length": 5,
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand}_0 < {threshold}",
                "short": "{left_operand}_0 > {threshold}",
            },
            "scale_type": "oscillator_0_100",
            "thresholds": {
                "aggressive": {"long_lt": 15, "short_gt": 85},
                "conservative": {"long_lt": 25, "short_gt": 75},
                "normal": {"long_lt": 20, "short_gt": 80},
            },
            "type": "momentum",
        },
    },
    "STOCHRSI": {
        "config": {
            "result_type": "complex",
            "scale_type": "oscillator_0_100",
            "category": "momentum",
            "adapter_function": "app.services.indicators.technical_indicators.momentum.MomentumIndicators.stochrsi",
            "required_data": ["close"],
            "output_names": ["STOCHRSI_K", "STOCHRSI_D"],
            "default_output": "STOCHRSI_K",
            "aliases": ["STOCHRSI"],
            "param_map": {
                "close": "data",
                "rsi_length": "rsi_length",
                "stoch_length": "stoch_length",
                "k": "k",
                "d": "d",
            },
            "parameters": {
                "rsi_length": {
                    "default_value": 14,
                    "min_value": 2,
                    "max_value": 50,
                    "description": "RSI計算期間",
                },
                "stoch_length": {
                    "default_value": 14,
                    "min_value": 2,
                    "max_value": 50,
                    "description": "Stochastic計算期間",
                },
                "k": {
                    "default_value": 3,
                    "min_value": 1,
                    "max_value": 10,
                    "description": "K平滑化期間",
                },
                "d": {
                    "default_value": 3,
                    "min_value": 1,
                    "max_value": 10,
                    "description": "D平滑化期間",
                },
            },
            "pandas_function": "stochrsi",
            "data_column": "Close",
            "data_columns": None,
            "returns": "multiple",
            "return_cols": ["STOCHRSIk", "STOCHRSId"],
            "multi_column": False,
            "default_values": {"rsi_length": 14, "stoch_length": 14, "k": 3, "d": 3},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand}_0 > {threshold}",
                "short": "{left_operand}_0 < {threshold}",
            },
            "scale_type": "oscillator_0_100",
            "thresholds": {
                "aggressive": {"long_gt": 70, "short_lt": 30},
                "conservative": {"long_gt": 80, "short_lt": 20},
                "normal": {"long_gt": 75, "short_lt": 25},
            },
            "type": "momentum",
        },
    },
    "UO": {
        "config": {
            "result_type": "single",
            "scale_type": "oscillator_0_100",
            "category": "momentum",
            "adapter_function": "app.services.indicators.technical_indicators.momentum.MomentumIndicators.uo",
            "required_data": ["high", "low", "close"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {
                "high": "high",
                "low": "low",
                "close": "close",
                "fast": "fast",
                "medium": "medium",
                "slow": "slow",
            },
            "parameters": {
                "fast": {
                    "default_value": 7,
                    "min_value": 2,
                    "max_value": 50,
                    "description": "短期期間",
                },
                "medium": {
                    "default_value": 14,
                    "min_value": 3,
                    "max_value": 100,
                    "description": "中期期間",
                },
                "slow": {
                    "default_value": 28,
                    "min_value": 5,
                    "max_value": 200,
                    "description": "長期期間",
                },
            },
            "pandas_function": "uo",
            "data_column": None,
            "data_columns": ["High", "Low", "Close"],
            "returns": "single",
            "return_cols": None,
            "multi_column": True,
            "default_values": {"fast": 7, "medium": 14, "slow": 28},
            "min_length_func": None,
            # パラメータ依存関係制約: fast < medium < slow
            "parameter_constraints": [
                {"type": "less_than", "param1": "fast", "param2": "medium"},
                {"type": "less_than", "param1": "medium", "param2": "slow"},
            ],
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand} > {threshold}",
                "short": "{left_operand} < {threshold}",
            },
            "scale_type": "oscillator_0_100",
            "thresholds": {
                "aggressive": {"long_gt": 55, "short_lt": 45},
                "conservative": {"long_gt": 65, "short_lt": 35},
                "normal": {"long_gt": 60, "short_lt": 40},
            },
            "type": "momentum",
        },
    },
    "APO": {
        "config": {
            "result_type": "single",
            "scale_type": "momentum_zero_centered",
            "category": "momentum",
            "adapter_function": "app.services.indicators.technical_indicators.momentum.MomentumIndicators.apo",
            "required_data": ["close"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {
                "close": "data",
                "fast": "fast",
                "slow": "slow",
                "ma_mode": "ma_mode",
            },
            "parameters": {
                "fast": {
                    "default_value": 12,
                    "min_value": 2,
                    "max_value": 100,
                    "description": "短期EMA期間",
                },
                "slow": {
                    "default_value": 26,
                    "min_value": 5,
                    "max_value": 200,
                    "description": "長期EMA期間",
                },
                "ma_mode": {
                    "default_value": "ema",
                    "min_value": None,
                    "max_value": None,
                    "description": "移動平均モード",
                },
            },
            "pandas_function": "apo",
            "data_column": "Close",
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {"fast": 12, "slow": 26, "ma_mode": "ema"},
            "min_length_func": None,
            # パラメータ依存関係制約: fast期間 < slow期間
            "parameter_constraints": [
                {"type": "less_than", "param1": "fast", "param2": "slow"},
            ],
        },
        "yaml": {
            "conditions": {"long": "{left_operand} > 0", "short": "{left_operand} < 0"},
            "scale_type": "momentum_zero_centered",
            "thresholds": {"zero_cross": True},
            "type": "momentum",
        },
    },
    "WILLR": {
        "config": {
            "result_type": "single",
            "scale_type": "oscillator_plus_minus_100",
            "category": "momentum",
            "adapter_function": "app.services.indicators.technical_indicators.momentum.MomentumIndicators.willr",
            "required_data": ["high", "low", "close"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {"period": "length"},
            "parameters": {
                "period": {
                    "default_value": 14,
                    "min_value": 2,
                    "max_value": 100,
                    "description": "Williams %R計算期間",
                }
            },
            "pandas_function": None,
            "data_column": None,
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {"period": 14},
            "min_length_func": None,
            "absolute_min_length": 3,
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand} > {threshold}",
                "short": "{left_operand} < {threshold}",
            },
            "scale_type": "oscillator_plus_minus_100",
            "thresholds": {
                "aggressive": {"long_lt": -95, "short_gt": -5},
                "conservative": {"long_lt": -75, "short_gt": -25},
                "normal": {"long_lt": -80, "short_gt": -20},
            },
            "type": "momentum",
        },
    },
    "STC": {
        "config": {
            "result_type": "single",
            "scale_type": "oscillator_0_100",
            "category": "momentum",
            "adapter_function": "app.services.indicators.technical_indicators.momentum.MomentumIndicators.stc",
            "required_data": ["close"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {
                "close": "data",
                "fast": "fast",
                "slow": "slow",
                "cycle": "cycle",
                "d1": "d1",
                "d2": "d2",
            },
            "parameters": {
                "fast": {
                    "default_value": 23,
                    "min_value": 2,
                    "max_value": 50,
                    "description": "STC fast period",
                },
                "slow": {
                    "default_value": 50,
                    "min_value": 5,
                    "max_value": 100,
                    "description": "STC slow period",
                },
                "cycle": {
                    "default_value": 10,
                    "min_value": 3,
                    "max_value": 50,
                    "description": "STC cycle period",
                },
                "d1": {
                    "default_value": 3,
                    "min_value": 2,
                    "max_value": 20,
                    "description": "STC first smoothing",
                },
                "d2": {
                    "default_value": 3,
                    "min_value": 2,
                    "max_value": 20,
                    "description": "STC second smoothing",
                },
            },
            "pandas_function": "stc",
            "data_column": "Close",
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {"fast": 23, "slow": 50, "cycle": 10, "d1": 3, "d2": 3},
            "min_length_func": None,
            # パラメータ依存関係制約: fast期間 < slow期間
            "parameter_constraints": [
                {"type": "less_than", "param1": "fast", "param2": "slow"},
            ],
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand} < {threshold}",
                "short": "{left_operand} > {threshold}",
            },
            "scale_type": "oscillator_0_100",
            "thresholds": {
                "aggressive": {"long_lt": 25, "short_gt": 75},
                "conservative": {"long_lt": 35, "short_gt": 65},
                "normal": {"long_lt": 30, "short_gt": 70},
            },
            "type": "momentum",
        },
    },
    "TRIX": {
        "config": {
            "result_type": "complex",
            "scale_type": "momentum_zero_centered",
            "category": "momentum",
            "adapter_function": "app.services.indicators.technical_indicators.momentum.MomentumIndicators.trix",
            "required_data": ["close"],
            "output_names": ["TRIX_Value", "TRIX_Signal", "TRIX_Histogram"],
            "default_output": "TRIX_Value",
            "aliases": None,
            "param_map": {
                "close": "data",
                "length": "length",
                "signal": "signal",
                "scalar": "scalar",
                "drift": "drift",
                "offset": "offset",
            },
            "parameters": {
                "length": {
                    "default_value": 15,
                    "min_value": 2,
                    "max_value": 200,
                    "description": "TRIX計算期間",
                },
                "signal": {
                    "default_value": 9,
                    "min_value": 1,
                    "max_value": 50,
                    "description": "シグナル期間",
                },
                "scalar": {
                    "default_value": 100.0,
                    "min_value": 1.0,
                    "max_value": 200.0,
                    "description": "スケール調整係数",
                },
                "drift": {
                    "default_value": 1,
                    "min_value": 1,
                    "max_value": 10,
                    "description": "ドリフト期間",
                },
                "offset": {
                    "default_value": 0,
                    "min_value": -10,
                    "max_value": 10,
                    "description": "出力オフセット",
                },
            },
            "pandas_function": None,
            "data_column": None,
            "data_columns": None,
            "returns": "multiple",
            "return_cols": None,
            "multi_column": False,
            "default_values": {
                "length": 15,
                "signal": 9,
                "scalar": 100.0,
                "drift": 1,
                "offset": 0,
            },
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand}_0 > {left_operand}_1",
                "short": "{left_operand}_0 < {left_operand}_1",
            },
            "scale_type": "momentum_zero_centered",
            "thresholds": {"zero_cross": True},
            "type": "momentum",
        },
    },
    "TSI": {
        "config": {
            "result_type": "complex",
            "scale_type": "oscillator_0_100",
            "category": "momentum",
            "adapter_function": "app.services.indicators.technical_indicators.momentum.MomentumIndicators.tsi",
            "required_data": ["close"],
            "output_names": ["TSI_0", "TSI_1"],
            "default_output": "TSI_0",
            "aliases": None,
            "param_map": {
                "close": "data",
                "fast": "fast",
                "slow": "slow",
                "signal": "signal",
                "scalar": "scalar",
                "mamode": "mamode",
                "drift": "drift",
            },
            "parameters": {
                "fast": {
                    "default_value": 13,
                    "min_value": 2,
                    "max_value": 50,
                    "description": "TSI短期期間",
                },
                "slow": {
                    "default_value": 25,
                    "min_value": 5,
                    "max_value": 50,
                    "description": "TSI長期期間",
                },
                "signal": {
                    "default_value": 13,
                    "min_value": 1,
                    "max_value": 50,
                    "description": "TSIシグナル期間",
                },
                "scalar": {
                    "default_value": 100.0,
                    "min_value": 1.0,
                    "max_value": 200.0,
                    "description": "TSIスカラー",
                },
                "mamode": {
                    "default_value": "ema",
                    "min_value": None,
                    "max_value": None,
                    "description": "移動平均モード",
                },
                "drift": {
                    "default_value": 1,
                    "min_value": 1,
                    "max_value": 10,
                    "description": "ドリフト期間",
                },
            },
            "pandas_function": "tsi",
            "data_column": "Close",
            "data_columns": None,
            "returns": "multiple",
            "return_cols": ["TSI", "TSIs"],
            "multi_column": False,
            "default_values": {
                "fast": 13,
                "slow": 25,
                "signal": 13,
                "scalar": 100.0,
                "mamode": "ema",
                "drift": 1,
            },
            "min_length_func": None,
            "absolute_min_length": 5,
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand}_0 > {threshold}",
                "short": "{left_operand}_0 < {threshold}",
            },
            "scale_type": "oscillator_0_100",
            "thresholds": {
                "aggressive": {"long_gt": 25, "short_lt": -25},
                "conservative": {"long_gt": 40, "short_lt": -40},
                "normal": {"long_gt": 30, "short_lt": -30},
            },
            "type": "momentum",
        },
    },
    "PGO": {
        "config": {
            "result_type": "single",
            "scale_type": "oscillator_plus_minus_100",
            "category": "momentum",
            "adapter_function": "app.services.indicators.technical_indicators.momentum.MomentumIndicators.pgo",
            "required_data": ["high", "low", "close"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {
                "high": "high",
                "low": "low",
                "close": "close",
                "length": "length",
            },
            "parameters": {
                "length": {
                    "default_value": 14,
                    "min_value": 2,
                    "max_value": 50,
                    "description": "PGO計算期間",
                }
            },
            "pandas_function": None,
            "data_column": None,
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {"length": 14},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand} > {threshold}",
                "short": "{left_operand} < {threshold}",
            },
            "scale_type": "oscillator_plus_minus_100",
            "thresholds": {
                "aggressive": {"long_gt": 10, "short_lt": -10},
                "conservative": {"long_gt": 40, "short_lt": -40},
                "normal": {"long_gt": 25, "short_lt": -25},
            },
            "type": "momentum",
        },
    },
    "MASSI": {
        "config": {
            "result_type": "single",
            "scale_type": "oscillator_0_100",
            "category": "momentum",
            "adapter_function": "app.services.indicators.technical_indicators.momentum.MomentumIndicators.massi",
            "required_data": ["high", "low"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {"high": "high", "low": "low", "fast": "fast", "slow": "slow"},
            "parameters": {
                "fast": {
                    "default_value": 9,
                    "min_value": 2,
                    "max_value": 20,
                    "description": "短期EMA期間",
                },
                "slow": {
                    "default_value": 25,
                    "min_value": 10,
                    "max_value": 50,
                    "description": "長期EMA期間",
                },
            },
            "pandas_function": None,
            "data_column": None,
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {"fast": 9, "slow": 25},
            "min_length_func": None,
            # パラメータ依存関係制約: fast期間 < slow期間
            "parameter_constraints": [
                {"type": "less_than", "param1": "fast", "param2": "slow"},
            ],
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand} > {threshold}",
                "short": "{left_operand} < {threshold}",
            },
            "scale_type": "oscillator_0_100",
            "thresholds": {
                "aggressive": {"long_gt": 85, "short_lt": 65},
                "conservative": {"long_gt": 95, "short_lt": 85},
                "normal": {"long_gt": 90, "short_lt": 75},
            },
            "type": "momentum",
        },
    },
    "PSL": {
        "config": {
            "result_type": "single",
            "scale_type": "oscillator_0_100",
            "category": "momentum",
            "adapter_function": "app.services.indicators.technical_indicators.momentum.MomentumIndicators.psl",
            "required_data": ["close"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {
                "close": "close",
                "length": "length",
                "scalar": "scalar",
                "drift": "drift",
                "open_": "open_",
            },
            "parameters": {
                "length": {
                    "default_value": 12,
                    "min_value": 2,
                    "max_value": 50,
                    "description": "心理ライン期間",
                },
                "scalar": {
                    "default_value": 100.0,
                    "min_value": 1.0,
                    "max_value": 200.0,
                    "description": "スケーリング係数",
                },
                "drift": {
                    "default_value": 1,
                    "min_value": 1,
                    "max_value": 10,
                    "description": "ドリフト期間",
                },
                "open_": {
                    "default_value": None,
                    "min_value": None,
                    "max_value": None,
                    "description": "始値データ",
                },
            },
            "pandas_function": None,
            "data_column": None,
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {
                "length": 12,
                "scalar": 100.0,
                "drift": 1,
                "open_": None,
            },
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand} > {threshold}",
                "short": "{left_operand} < {threshold}",
            },
            "scale_type": "oscillator_0_100",
            "thresholds": {
                "aggressive": {"long_gt": 65, "short_lt": 35},
                "conservative": {"long_gt": 80, "short_lt": 20},
                "normal": {"long_gt": 75, "short_lt": 25},
            },
            "type": "momentum",
        },
    },
    "AO": {
        "config": {
            "result_type": "single",
            "scale_type": "momentum_zero_centered",
            "category": "momentum",
            "adapter_function": "app.services.indicators.technical_indicators.momentum.MomentumIndicators.ao",
            "required_data": ["high", "low"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {"high": "high", "low": "low", "fast": "fast", "slow": "slow"},
            "parameters": {
                "fast": {
                    "default_value": 5,
                    "min_value": 2,
                    "max_value": 20,
                    "description": "AO短期期間",
                },
                "slow": {
                    "default_value": 34,
                    "min_value": 10,
                    "max_value": 50,
                    "description": "AO長期期間",
                },
            },
            "pandas_function": "ao",
            "data_column": None,
            "data_columns": ["High", "Low"],
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {"fast": 5, "slow": 34},
            "min_length_func": None,
            # パラメータ依存関係制約: fast期間 < slow期間
            "parameter_constraints": [
                {"type": "less_than", "param1": "fast", "param2": "slow"},
            ],
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand} > {threshold}",
                "short": "{left_operand} < {threshold}",
            },
            "scale_type": "momentum_zero_centered",
            "thresholds": {
                "aggressive": {"long_gt": 0.1, "short_lt": -0.1},
                "conservative": {"long_gt": 0.3, "short_lt": -0.3},
                "normal": {"long_gt": 0.2, "short_lt": -0.2},
            },
            "type": "momentum",
        },
    },
    "BOP": {
        "config": {
            "result_type": "single",
            "scale_type": "momentum_zero_centered",
            "category": "momentum",
            "adapter_function": "app.services.indicators.technical_indicators.momentum.MomentumIndicators.bop",
            "required_data": ["open", "high", "low", "close"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {
                "open": "open_",
                "high": "high",
                "low": "low",
                "close": "close",
            },
            "parameters": {},
            "pandas_function": "bop",
            "data_column": None,
            "data_columns": ["Open", "High", "Low", "Close"],
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand} > {threshold}",
                "short": "{left_operand} < {threshold}",
            },
            "scale_type": "momentum_zero_centered",
            "thresholds": {
                "aggressive": {"long_gt": 0.1, "short_lt": -0.1},
                "conservative": {"long_gt": 0.3, "short_lt": -0.3},
                "normal": {"long_gt": 0.2, "short_lt": -0.2},
            },
            "type": "momentum",
        },
    },
    "CG": {
        "config": {
            "result_type": "single",
            "scale_type": "oscillator_0_100",
            "category": "momentum",
            "adapter_function": "app.services.indicators.technical_indicators.momentum.MomentumIndicators.cg",
            "required_data": ["close"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {"close": "data", "length": "length"},
            "parameters": {
                "length": {
                    "default_value": 10,
                    "min_value": 2,
                    "max_value": 50,
                    "description": "CG期間",
                }
            },
            "pandas_function": "cg",
            "data_column": "Close",
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {"length": 10},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand} > {threshold}",
                "short": "{left_operand} < {threshold}",
            },
            "scale_type": "oscillator_0_100",
            "thresholds": {
                "aggressive": {"long_gt": 60, "short_lt": 40},
                "conservative": {"long_gt": 80, "short_lt": 20},
                "normal": {"long_gt": 70, "short_lt": 30},
            },
            "type": "momentum",
        },
    },
    "ICHIMOKU": {
        "config": {
            "result_type": "complex",
            "scale_type": "price_absolute",
            "category": "momentum",
            "adapter_function": "app.services.indicators.technical_indicators.momentum.MomentumIndicators.ichimoku",
            "required_data": ["high", "low", "close"],
            "output_names": [
                "ICHIMOKU_Tenkan",
                "ICHIMOKU_Kijun",
                "ICHIMOKU_Senkou_A",
                "ICHIMOKU_Senkou_B",
                "ICHIMOKU_Chikou",
            ],
            "default_output": "ICHIMOKU_Tenkan",
            "aliases": ["ICHIMOKU"],
            "param_map": {
                "high": "high",
                "low": "low",
                "close": "close",
                "tenkan_period": "tenkan_period",
                "kijun_period": "kijun_period",
                "senkou_span_b_period": "senkou_span_b_period",
            },
            "parameters": {
                "tenkan_period": {
                    "default_value": 9,
                    "min_value": 3,
                    "max_value": 50,
                    "description": "Tenkan-sen (conversion line) period",
                },
                "kijun_period": {
                    "default_value": 26,
                    "min_value": 10,
                    "max_value": 100,
                    "description": "Kijun-sen (base line) period",
                },
                "senkou_span_b_period": {
                    "default_value": 52,
                    "min_value": 20,
                    "max_value": 200,
                    "description": "Senkou Span B (leading span B) period",
                },
            },
            "pandas_function": "ichimoku",
            "data_column": None,
            "data_columns": ["High", "Low", "Close"],
            "returns": "multiple",
            "return_cols": ["TENKAN", "KIJUN", "SENKOU", "SANSEN", "CHIKOU"],
            "multi_column": True,
            "default_values": {
                "tenkan_period": 9,
                "kijun_period": 26,
                "senkou_span_b_period": 52,
            },
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand}_tenkan_sen > {left_operand}_kijun_sen",
                "short": "{left_operand}_tenkan_sen < {left_operand}_kijun_sen",
            },
            "scale_type": "price_absolute",
            "thresholds": {
                "aggressive": {"tenkan_gt_kijun": True},
                "conservative": {"tenkan_gt_kijun": False},
                "normal": {"tenkan_gt_kijun": True},
            },
            "type": "momentum",
        },
    },
    "COPPOCK": {
        "config": {
            "result_type": "single",
            "scale_type": "oscillator_0_100",
            "category": "momentum",
            "adapter_function": "app.services.indicators.technical_indicators.momentum.MomentumIndicators.coppock",
            "required_data": ["close"],
            "output_names": None,
            "default_output": None,
            "aliases": ["COPC"],
            "param_map": {
                "close": "close",
                "length": "length",
                "fast": "fast",
                "slow": "slow",
            },
            "parameters": {
                "length": {
                    "default_value": 11,
                    "min_value": 5,
                    "max_value": 30,
                    "description": "Coppock主期間",
                },
                "fast": {
                    "default_value": 14,
                    "min_value": 5,
                    "max_value": 30,
                    "description": "短期期間",
                },
                "slow": {
                    "default_value": 10,
                    "min_value": 5,
                    "max_value": 30,
                    "description": "長期期間",
                },
            },
            "pandas_function": "coppock",
            "data_column": "Close",
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {"length": 11, "fast": 14, "slow": 10},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand} > {threshold}",
                "short": "{left_operand} < {threshold}",
            },
            "scale_type": "oscillator_0_100",
            "thresholds": {
                "aggressive": {"long_gt": 50, "short_lt": 30},
                "conservative": {"long_gt": 80, "short_lt": 20},
                "normal": {"long_gt": 60, "short_lt": 40},
            },
            "type": "momentum",
        },
    },
    "WPR": {
        "config": {
            "result_type": "single",
            "scale_type": "oscillator_0_100",
            "category": "momentum",
            "adapter_function": "app.services.indicators.technical_indicators.momentum.MomentumIndicators.willr",
            "required_data": ["high", "low", "close"],
            "output_names": None,
            "default_output": None,
            "aliases": ["Williams_%R", "Williams_R"],
            "param_map": {
                "high": "high",
                "low": "low",
                "close": "close",
                "length": "length",
            },
            "parameters": {
                "length": {
                    "default_value": 14,
                    "min_value": 2,
                    "max_value": 100,
                    "description": "Williams %R計算期間",
                }
            },
            "pandas_function": "wpr",
            "data_column": None,
            "data_columns": ["High", "Low", "Close"],
            "returns": "single",
            "return_cols": None,
            "multi_column": True,
            "default_values": {"length": 14},
            "min_length_func": None,
            "absolute_min_length": 3,
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand} < {threshold}",
                "short": "{left_operand} > {threshold}",
            },
            "scale_type": "oscillator_0_100",
            "thresholds": {
                "aggressive": {"long_lt": 20, "short_gt": 80},
                "conservative": {"long_lt": 10, "short_gt": 90},
                "normal": {"long_lt": 15, "short_gt": 85},
            },
            "type": "momentum",
        },
    },
    "PSY": {
        "config": {
            "result_type": "single",
            "scale_type": "oscillator_0_100",
            "category": "momentum",
            "adapter_function": "app.services.indicators.technical_indicators.momentum.MomentumIndicators.psl",
            "required_data": ["close"],
            "output_names": None,
            "default_output": None,
            "aliases": ["Psychological_Line", "PSY"],
            "param_map": {"close": "close", "length": "length", "offset": "offset"},
            "parameters": {
                "length": {
                    "default_value": 12,
                    "min_value": 5,
                    "max_value": 30,
                    "description": "Psychological Line計算期間",
                },
                "offset": {
                    "default_value": 0,
                    "min_value": -10,
                    "max_value": 10,
                    "description": "出力オフセット",
                },
            },
            "pandas_function": "psl",
            "data_column": "Close",
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {"length": 12, "offset": 0},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand} > {threshold}",
                "short": "{left_operand} < {threshold}",
            },
            "scale_type": "oscillator_0_100",
            "thresholds": {
                "aggressive": {"long_gt": 75, "short_lt": 25},
                "conservative": {"long_gt": 80, "short_lt": 20},
                "normal": {"long_gt": 70, "short_lt": 30},
            },
            "type": "momentum",
        },
    },
}
