from __future__ import annotations

from typing import Any, Dict

MANIFEST_ORIGINAL: Dict[str, Dict[str, Any]] = {
    "ELDER_RAY": {
        "config": {
            "result_type": "complex",
            "scale_type": "momentum_zero_centered",
            "category": "original",
            "adapter_function": "app.services.indicators.technical_indicators.original.OriginalIndicators.elder_ray",
            "required_data": ["high", "low", "close"],
            "output_names": ["ELDER_RAY_Bull", "ELDER_RAY_Bear"],
            "default_output": "ELDER_RAY_Bull",
            "aliases": None,
            "param_map": {
                "high": "high",
                "low": "low",
                "close": "close",
                "length": "length",
                "ema_length": "ema_length",
            },
            "parameters": {
                "length": {
                    "default_value": 13,
                    "min_value": 5,
                    "max_value": 50,
                    "description": "Elder Ray計算期間",
                },
                "ema_length": {
                    "default_value": 16,
                    "min_value": 5,
                    "max_value": 50,
                    "description": "EMA計算期間",
                },
            },
            "pandas_function": None,
            "data_column": None,
            "data_columns": ["High", "Low", "Close"],
            "returns": "multiple",
            "return_cols": ["BULL", "BEAR"],
            "multi_column": True,
            "default_values": {"length": 13, "ema_length": 16},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand}_0 > {threshold}",
                "short": "{left_operand}_1 < {threshold}",
            },
            "scale_type": "momentum_zero_centered",
            "thresholds": {
                "aggressive": {"long_gt": 0.5, "short_lt": -0.5},
                "conservative": {"long_gt": 1.5, "short_lt": -1.5},
                "normal": {"long_gt": 1.0, "short_lt": -1.0},
            },
            "type": "momentum",
        },
    },
    "ADAPTIVE_ENTROPY": {
        "config": {
            "result_type": "complex",
            "scale_type": "oscillator_plus_minus_100",
            "category": "original",
            "adapter_function": "app.services.indicators.technical_indicators.original.OriginalIndicators.adaptive_entropy",
            "required_data": ["close"],
            "output_names": [
                "ADAPTIVE_ENTROPY_OSC",
                "ADAPTIVE_ENTROPY_SIGNAL",
                "ADAPTIVE_ENTROPY_RATIO",
            ],
            "default_output": "ADAPTIVE_ENTROPY_OSC",
            "aliases": None,
            "param_map": {
                "close": "close",
                "short_length": "short_length",
                "long_length": "long_length",
                "signal_length": "signal_length",
            },
            "parameters": {
                "short_length": {
                    "default_value": 14,
                    "min_value": 5,
                    "max_value": 50,
                    "description": "短期エントロピー計算期間",
                },
                "long_length": {
                    "default_value": 28,
                    "min_value": 10,
                    "max_value": 100,
                    "description": "長期エントロピー計算期間",
                },
                "signal_length": {
                    "default_value": 5,
                    "min_value": 2,
                    "max_value": 20,
                    "description": "信号線平滑化期間",
                },
            },
            "pandas_function": None,
            "data_column": None,
            "data_columns": None,
            "returns": "multiple",
            "return_cols": ["OSC", "SIGNAL", "RATIO"],
            "multi_column": False,
            "default_values": {
                "short_length": 14,
                "long_length": 28,
                "signal_length": 5,
            },
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand}_1 > {left_operand}_0",
                "short": "{left_operand}_1 < {left_operand}_0",
            },
            "scale_type": "oscillator_zero_centered",
            "thresholds": {
                "aggressive": {"long_gt": 0.2, "short_lt": -0.2},
                "conservative": {"long_gt": 0.8, "short_lt": -0.8},
                "normal": {"long_gt": 0.5, "short_lt": -0.5},
            },
            "type": "original",
        },
    },
    "QUANTUM_FLOW": {
        "config": {
            "result_type": "complex",
            "scale_type": "oscillator_plus_minus_100",
            "category": "original",
            "adapter_function": "app.services.indicators.technical_indicators.original.OriginalIndicators.quantum_flow",
            "required_data": ["close", "high", "low", "volume"],
            "output_names": ["QUANTUM_FLOW", "QUANTUM_FLOW_SIGNAL"],
            "default_output": "QUANTUM_FLOW",
            "aliases": None,
            "param_map": {
                "close": "close",
                "high": "high",
                "low": "low",
                "volume": "volume",
                "length": "length",
                "flow_length": "flow_length",
            },
            "parameters": {
                "length": {
                    "default_value": 14,
                    "min_value": 5,
                    "max_value": 50,
                    "description": "ウェーブレット計算期間",
                },
                "flow_length": {
                    "default_value": 9,
                    "min_value": 3,
                    "max_value": 20,
                    "description": "フロースコア計算期間",
                },
            },
            "pandas_function": None,
            "data_column": None,
            "data_columns": ["Close", "High", "Low", "Volume"],
            "returns": "multiple",
            "return_cols": ["FLOW", "SIGNAL"],
            "multi_column": False,
            "default_values": {"length": 14, "flow_length": 9},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand}_1 > {left_operand}_0",
                "short": "{left_operand}_1 < {left_operand}_0",
            },
            "scale_type": "oscillator_zero_centered",
            "thresholds": {
                "aggressive": {"long_gt": 0.1, "short_lt": -0.1},
                "conservative": {"long_gt": 0.3, "short_lt": -0.3},
                "normal": {"long_gt": 0.2, "short_lt": -0.2},
            },
            "type": "original",
        },
    },
    "HARMONIC_RESONANCE": {
        "config": {
            "result_type": "complex",
            "scale_type": "oscillator_plus_minus_100",
            "category": "original",
            "adapter_function": "app.services.indicators.technical_indicators.original.OriginalIndicators.harmonic_resonance",
            "required_data": ["close", "high", "low"],
            "output_names": ["HARMONIC_RESONANCE", "HRI_SIGNAL"],
            "default_output": "HARMONIC_RESONANCE",
            "aliases": None,
            "param_map": {
                "close": "close",
                "high": "high",
                "low": "low",
                "length": "length",
                "resonance_bands": "resonance_bands",
                "signal_length": "signal_length",
            },
            "parameters": {
                "length": {
                    "default_value": 20,
                    "min_value": 10,
                    "max_value": 50,
                    "description": "主計算期間",
                },
                "resonance_bands": {
                    "default_value": 5,
                    "min_value": 3,
                    "max_value": 10,
                    "description": "共振バンド数",
                },
                "signal_length": {
                    "default_value": 3,
                    "min_value": 2,
                    "max_value": 10,
                    "description": "信号線平滑化期間",
                },
            },
            "pandas_function": None,
            "data_column": None,
            "data_columns": ["Close", "High", "Low"],
            "returns": "multiple",
            "return_cols": ["HRI", "SIGNAL"],
            "multi_column": False,
            "default_values": {"length": 20, "resonance_bands": 5, "signal_length": 3},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand}_1 > {left_operand}_0",
                "short": "{left_operand}_1 < {left_operand}_0",
            },
            "scale_type": "oscillator_plus_minus_100",
            "thresholds": {
                "aggressive": {"long_gt": 50, "short_lt": -50},
                "conservative": {"long_gt": 150, "short_lt": -150},
                "normal": {"long_gt": 100, "short_lt": -100},
            },
            "type": "original",
        },
    },
    "CHAOS_FRACTAL_DIM": {
        "config": {
            "result_type": "complex",
            "scale_type": "oscillator_plus_minus_100",
            "category": "original",
            "adapter_function": "app.services.indicators.technical_indicators.original.OriginalIndicators.chaos_fractal_dimension",
            "required_data": ["close", "high", "low", "volume"],
            "output_names": ["CHAOS_FRACTAL_DIM", "CTFD_SIGNAL"],
            "default_output": "CHAOS_FRACTAL_DIM",
            "aliases": None,
            "param_map": {
                "close": "close",
                "high": "high",
                "low": "low",
                "volume": "volume",
                "length": "length",
                "embedding_dim": "embedding_dim",
                "signal_length": "signal_length",
            },
            "parameters": {
                "length": {
                    "default_value": 25,
                    "min_value": 15,
                    "max_value": 60,
                    "description": "主計算期間",
                },
                "embedding_dim": {
                    "default_value": 3,
                    "min_value": 2,
                    "max_value": 5,
                    "description": "埋め込み次元数",
                },
                "signal_length": {
                    "default_value": 4,
                    "min_value": 2,
                    "max_value": 10,
                    "description": "信号線平滑化期間",
                },
            },
            "pandas_function": None,
            "data_column": None,
            "data_columns": ["Close", "High", "Low", "Volume"],
            "returns": "multiple",
            "return_cols": ["CTFD", "SIGNAL"],
            "multi_column": False,
            "default_values": {"length": 25, "embedding_dim": 3, "signal_length": 4},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand}_1 > {left_operand}_0",
                "short": "{left_operand}_1 < {left_operand}_0",
            },
            "scale_type": "oscillator_plus_minus_100",
            "thresholds": {
                "aggressive": {"long_gt": 20, "short_lt": -20},
                "conservative": {"long_gt": 60, "short_lt": -60},
                "normal": {"long_gt": 40, "short_lt": -40},
            },
            "type": "original",
        },
    },
    "PRIME_OSC": {
        "config": {
            "result_type": "complex",
            "scale_type": "momentum_zero_centered",
            "category": "original",
            "adapter_function": "app.services.indicators.technical_indicators.original.OriginalIndicators.prime_oscillator",
            "required_data": ["close"],
            "output_names": ["PRIME_OSC", "PRIME_SIGNAL"],
            "default_output": "PRIME_OSC",
            "aliases": ["Prime_Oscillator"],
            "param_map": {
                "close": "close",
                "length": "length",
                "signal_length": "signal_length",
            },
            "parameters": {
                "length": {
                    "default_value": 14,
                    "min_value": 2,
                    "max_value": 50,
                    "description": "Prime Number Oscillator計算期間",
                },
                "signal_length": {
                    "default_value": 3,
                    "min_value": 2,
                    "max_value": 20,
                    "description": "Signal line計算期間",
                },
            },
            "pandas_function": None,
            "data_column": None,
            "data_columns": None,
            "returns": "multiple",
            "return_cols": None,
            "multi_column": False,
            "default_values": {"length": 14, "signal_length": 3},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand}_0 > {left_operand}_1",
                "short": "{left_operand}_0 < {left_operand}_1",
            },
            "scale_type": "momentum_zero_centered",
            "thresholds": {
                "aggressive": {"long_gt": 5, "short_lt": -5},
                "conservative": {"long_gt": 15, "short_lt": -15},
                "normal": {"long_gt": 10, "short_lt": -10},
            },
            "type": "original",
        },
    },
    "FIBO_CYCLE": {
        "config": {
            "result_type": "complex",
            "scale_type": "momentum_zero_centered",
            "category": "original",
            "adapter_function": "app.services.indicators.technical_indicators.original.OriginalIndicators.fibonacci_cycle",
            "required_data": ["close"],
            "output_names": ["FIBO_CYCLE", "FIBO_SIGNAL"],
            "default_output": "FIBO_CYCLE",
            "aliases": ["Fibonacci_Cycle"],
            "param_map": {
                "close": "close",
                "cycle_periods": "cycle_periods",
                "fib_ratios": "fib_ratios",
            },
            "parameters": {
                "cycle_periods": {
                    "default_value": [8, 13, 21, 34, 55],
                    "min_value": None,
                    "max_value": None,
                    "description": "Fibonacci Cycle計算に使用する期間リスト",
                },
                "fib_ratios": {
                    "default_value": [0.618, 1.0, 1.618, 2.618],
                    "min_value": None,
                    "max_value": None,
                    "description": "Fibonacci比率リスト",
                },
            },
            "pandas_function": None,
            "data_column": None,
            "data_columns": None,
            "returns": "multiple",
            "return_cols": None,
            "multi_column": False,
            "default_values": {
                "cycle_periods": [8, 13, 21, 34, 55],
                "fib_ratios": [0.618, 1.0, 1.618, 2.618],
            },
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand}_0 > {left_operand}_1",
                "short": "{left_operand}_0 < {left_operand}_1",
            },
            "scale_type": "momentum_zero_centered",
            "thresholds": {
                "aggressive": {"long_gt": 0.5, "short_lt": -0.5},
                "conservative": {"long_gt": 2.0, "short_lt": -2.0},
                "normal": {"long_gt": 1.0, "short_lt": -1.0},
            },
            "type": "original",
        },
    },
    "MCGINLEY_DYNAMIC": {
        "config": {
            "result_type": "single",
            "scale_type": "price_absolute",
            "category": "original",
            "adapter_function": "app.services.indicators.technical_indicators.original.OriginalIndicators.mcginley_dynamic",
            "required_data": ["close"],
            "output_names": None,
            "default_output": None,
            "aliases": ["McGinley_Dynamic", "MD"],
            "param_map": {"close": "close", "length": "length", "k": "k"},
            "parameters": {
                "length": {
                    "default_value": 10,
                    "min_value": 1,
                    "max_value": 200,
                    "description": "McGinley Dynamic計算期間",
                },
                "k": {
                    "default_value": 0.6,
                    "min_value": 0.1,
                    "max_value": 2.0,
                    "description": "適応係数（小さいほど反応が速い）",
                },
            },
            "pandas_function": None,
            "data_column": None,
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {"length": 10, "k": 0.6},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "close > {left_operand}",
                "short": "close < {left_operand}",
            },
            "scale_type": "price_absolute",
            "thresholds": {
                "aggressive": {"long_gt": 0.0, "short_lt": 0.0},
                "conservative": {"long_gt": 0.0, "short_lt": 0.0},
                "normal": {"long_gt": 0.0, "short_lt": 0.0},
            },
            "type": "original",
        },
    },
    "KAUFMAN_EFFICIENCY_RATIO": {
        "config": {
            "result_type": "single",
            "scale_type": "oscillator_0_100",
            "category": "original",
            "adapter_function": "app.services.indicators.technical_indicators.trend.TrendIndicators.efficiency_ratio",
            "required_data": ["close"],
            "output_names": None,
            "default_output": None,
            "aliases": ["Kaufman_ER", "KER"],
            "param_map": {"close": "data", "length": "length"},
            "parameters": {
                "length": {
                    "default_value": 10,
                    "min_value": 2,
                    "max_value": 100,
                    "description": "Efficiency Ratio計算期間",
                }
            },
            "pandas_function": None,
            "data_column": None,
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {"length": 10},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand} > 0.5",
                "short": "{left_operand} < 0.3",
            },
            "scale_type": "oscillator_0_100",
            "thresholds": {
                "aggressive": {"long_gt": 0.4, "short_lt": 0.4},
                "conservative": {"long_gt": 0.6, "short_lt": 0.2},
                "normal": {"long_gt": 0.5, "short_lt": 0.3},
            },
            "type": "original",
        },
    },
    "CHANDE_KROLL_STOP": {
        "config": {
            "result_type": "complex",
            "scale_type": "price_absolute",
            "category": "original",
            "adapter_function": "app.services.indicators.technical_indicators.original.OriginalIndicators.chande_kroll_stop",
            "required_data": ["high", "low", "close"],
            "output_names": ["CKS_LONG", "CKS_SHORT"],
            "default_output": "CKS_LONG",
            "aliases": ["Chande_Kroll", "CKS"],
            "param_map": {
                "high": "high",
                "low": "low",
                "close": "close",
                "p": "p",
                "x": "x",
                "q": "q",
            },
            "parameters": {
                "p": {
                    "default_value": 10,
                    "min_value": 1,
                    "max_value": 50,
                    "description": "初期ストップ計算期間",
                },
                "x": {
                    "default_value": 1.0,
                    "min_value": 0.1,
                    "max_value": 5.0,
                    "description": "ATR乗数",
                },
                "q": {
                    "default_value": 9,
                    "min_value": 1,
                    "max_value": 50,
                    "description": "平滑化期間",
                },
            },
            "pandas_function": None,
            "data_column": None,
            "data_columns": None,
            "returns": "multiple",
            "return_cols": None,
            "multi_column": False,
            "default_values": {"p": 10, "x": 1.0, "q": 9},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "close > {left_operand}_0",
                "short": "close < {left_operand}_1",
            },
            "scale_type": "price_absolute",
            "thresholds": {
                "aggressive": {"long_gt": 0.0, "short_lt": 0.0},
                "conservative": {"long_gt": 0.0, "short_lt": 0.0},
                "normal": {"long_gt": 0.0, "short_lt": 0.0},
            },
            "type": "original",
        },
    },
    "TREND_INTENSITY_INDEX": {
        "config": {
            "result_type": "single",
            "scale_type": "oscillator_0_100",
            "category": "original",
            "adapter_function": "app.services.indicators.technical_indicators.original.OriginalIndicators.trend_intensity_index",
            "required_data": ["close", "high", "low"],
            "output_names": None,
            "default_output": None,
            "aliases": ["TII"],
            "param_map": {
                "close": "close",
                "high": "high",
                "low": "low",
                "length": "length",
                "sma_length": "sma_length",
            },
            "parameters": {
                "length": {
                    "default_value": 14,
                    "min_value": 1,
                    "max_value": 100,
                    "description": "カウント期間",
                },
                "sma_length": {
                    "default_value": 30,
                    "min_value": 1,
                    "max_value": 200,
                    "description": "SMA計算期間",
                },
            },
            "pandas_function": None,
            "data_column": None,
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {"length": 14, "sma_length": 30},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand} > 60",
                "short": "{left_operand} < 40",
            },
            "scale_type": "oscillator_0_100",
            "thresholds": {
                "aggressive": {"long_gt": 55, "short_lt": 45},
                "conservative": {"long_gt": 70, "short_lt": 30},
                "normal": {"long_gt": 60, "short_lt": 40},
            },
            "type": "original",
        },
    },
    "CONNORS_RSI": {
        "config": {
            "result_type": "single",
            "scale_type": "oscillator_0_100",
            "category": "original",
            "adapter_function": "app.services.indicators.technical_indicators.original.OriginalIndicators.connors_rsi",
            "required_data": ["close"],
            "output_names": None,
            "default_output": None,
            "aliases": ["ConnorsRSI"],
            "param_map": {
                "close": "close",
                "rsi_periods": "rsi_periods",
                "streak_periods": "streak_periods",
                "rank_periods": "rank_periods",
            },
            "parameters": {
                "rsi_periods": {
                    "default_value": 3,
                    "min_value": 2,
                    "max_value": 20,
                    "description": "Close RSI計算期間",
                },
                "streak_periods": {
                    "default_value": 2,
                    "min_value": 1,
                    "max_value": 10,
                    "description": "ストリークRSI計算期間",
                },
                "rank_periods": {
                    "default_value": 100,
                    "min_value": 10,
                    "max_value": 200,
                    "description": "ランク計算期間",
                },
            },
            "pandas_function": None,
            "data_column": None,
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {
                "rsi_periods": 3,
                "streak_periods": 2,
                "rank_periods": 100,
            },
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand} > 70",
                "short": "{left_operand} < 30",
            },
            "scale_type": "oscillator_0_100",
            "thresholds": {
                "aggressive": {"long_gt": 65, "short_lt": 35},
                "conservative": {"long_gt": 80, "short_lt": 20},
                "normal": {"long_gt": 70, "short_lt": 30},
            },
            "type": "original",
        },
    },
    "FRAC_DIFF": {
        "config": {
            "result_type": "single",
            "scale_type": "price_absolute",
            "category": "original",
            "adapter_function": "app.services.indicators.technical_indicators.advanced_features.AdvancedFeatures.frac_diff_ffd",
            "required_data": ["close"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {
                "close": "series",
                "d": "d",
                "thres": "thres",
                "window": "window",
            },
            "parameters": {
                "d": {
                    "default_value": 0.4,
                    "min_value": 0.0,
                    "max_value": 1.0,
                    "description": "Fractional differencing order",
                },
                "thres": {
                    "default_value": 1e-05,
                    "min_value": 1e-07,
                    "max_value": 0.1,
                    "description": "Weight threshold",
                },
                "window": {
                    "default_value": 2000,
                    "min_value": 100,
                    "max_value": 10000,
                    "description": "Weight window",
                },
            },
            "pandas_function": None,
            "data_column": "Close",
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {"d": 0.4, "thres": 1e-05, "window": 2000},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {},
            "scale_type": "price_absolute",
            "thresholds": None,
            "type": "original",
        },
    },
    "LIQUIDATION_CASCADE": {
        "config": {
            "result_type": "single",
            "scale_type": "momentum_zero_centered",
            "category": "original",
            "adapter_function": "app.services.indicators.technical_indicators.advanced_features.AdvancedFeatures.liquidation_cascade_score",
            "required_data": ["close", "volume", "open_interest"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {},
            "parameters": {},
            "pandas_function": None,
            "data_column": None,
            "data_columns": ["Close", "Volume", "open_interest"],
            "returns": "single",
            "return_cols": None,
            "multi_column": True,
            "default_values": {},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {},
            "scale_type": "momentum_zero_centered",
            "thresholds": None,
            "type": "original",
        },
    },
    "SQUEEZE_PROB": {
        "config": {
            "result_type": "single",
            "scale_type": "momentum_zero_centered",
            "category": "original",
            "adapter_function": "app.services.indicators.technical_indicators.advanced_features.AdvancedFeatures.squeeze_probability",
            "required_data": ["close", "low", "open_interest", "funding_rate"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {
                "lookback": "lookback",
            },
            "parameters": {
                "lookback": {
                    "default_value": 20,
                    "min_value": 2,
                    "max_value": 200,
                    "description": "Lookback for low",
                }
            },
            "pandas_function": None,
            "data_column": None,
            "data_columns": ["Close", "Low", "open_interest", "funding_rate"],
            "returns": "single",
            "return_cols": None,
            "multi_column": True,
            "default_values": {"lookback": 20},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {},
            "scale_type": "momentum_zero_centered",
            "thresholds": None,
            "type": "original",
        },
    },
    "TREND_QUALITY": {
        "config": {
            "result_type": "single",
            "scale_type": "oscillator_plus_minus_100",
            "category": "original",
            "adapter_function": "app.services.indicators.technical_indicators.advanced_features.AdvancedFeatures.trend_quality",
            "required_data": ["close", "open_interest"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {
                "window": "window",
            },
            "parameters": {
                "window": {
                    "default_value": 20,
                    "min_value": 2,
                    "max_value": 200,
                    "description": "Correlation window",
                }
            },
            "pandas_function": None,
            "data_column": None,
            "data_columns": ["Close", "open_interest"],
            "returns": "single",
            "return_cols": None,
            "multi_column": True,
            "default_values": {"window": 20},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {},
            "scale_type": "oscillator_plus_minus_100",
            "thresholds": None,
            "type": "original",
        },
    },
    "OI_WEIGHTED_FR": {
        "config": {
            "result_type": "single",
            "scale_type": "momentum_zero_centered",
            "category": "original",
            "adapter_function": "app.services.indicators.technical_indicators.advanced_features.AdvancedFeatures.oi_weighted_funding_rate",
            "required_data": ["open_interest", "funding_rate"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {},
            "parameters": {},
            "pandas_function": None,
            "data_column": None,
            "data_columns": ["open_interest", "funding_rate"],
            "returns": "single",
            "return_cols": None,
            "multi_column": True,
            "default_values": {},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {},
            "scale_type": "momentum_zero_centered",
            "thresholds": None,
            "type": "original",
        },
    },
    "LEVERAGE_RATIO": {
        "config": {
            "result_type": "single",
            "scale_type": "price_ratio",
            "category": "original",
            "adapter_function": "app.services.indicators.technical_indicators.advanced_features.AdvancedFeatures.leverage_ratio",
            "required_data": ["open_interest", "market_cap"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {},
            "parameters": {},
            "pandas_function": None,
            "data_column": None,
            "data_columns": ["open_interest", "market_cap"],
            "returns": "single",
            "return_cols": None,
            "multi_column": True,
            "default_values": {},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {},
            "scale_type": "price_ratio",
            "thresholds": None,
            "type": "original",
        },
    },
    "LIQUIDITY_EFFICIENCY": {
        "config": {
            "result_type": "single",
            "scale_type": "price_ratio",
            "category": "original",
            "adapter_function": "app.services.indicators.technical_indicators.advanced_features.AdvancedFeatures.liquidity_efficiency",
            "required_data": ["open_interest", "volume"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {},
            "parameters": {},
            "pandas_function": None,
            "data_column": None,
            "data_columns": ["open_interest", "Volume"],
            "returns": "single",
            "return_cols": None,
            "multi_column": True,
            "default_values": {},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {},
            "scale_type": "price_ratio",
            "thresholds": None,
            "type": "original",
        },
    },
}
