from __future__ import annotations

from typing import Any, Dict

MANIFEST_TREND: Dict[str, Dict[str, Any]] = {
    "ADX": {
        "config": {
            "result_type": "complex",
            "scale_type": "oscillator_0_100",
            "category": "trend",
            "adapter_function": "app.services.indicators.technical_indicators.trend.TrendIndicators.adx",
            "required_data": ["high", "low", "close"],
            "output_names": ["ADX", "DMP", "DMN"],
            "default_output": "ADX",
            "aliases": None,
            "param_map": {"period": "length"},
            "parameters": {
                "period": {
                    "default_value": 14,
                    "min_value": 2,
                    "max_value": 100,
                    "description": "ADX計算期間",
                }
            },
            "pandas_function": None,
            "data_column": None,
            "data_columns": None,
            "returns": "multiple",
            "return_cols": ["ADX", "DMP", "DMN"],
            "multi_column": True,
            "default_values": {"period": 14},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand} > {threshold}",
                "short": "{left_operand} > {threshold}",
            },
            "scale_type": "oscillator_0_100",
            "thresholds": {
                "aggressive": {"trend_min": 18},
                "conservative": {"trend_min": 30},
                "normal": {"trend_min": 25},
            },
            "type": "momentum",
        },
    },
    "ALMA": {
        "config": {
            "result_type": "single",
            "scale_type": "price_ratio",
            "category": "trend",
            "adapter_function": "app.services.indicators.technical_indicators.trend.TrendIndicators.alma",
            "required_data": ["close"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {
                "close": "data",
                "length": "length",
                "sigma": "sigma",
                "distribution_offset": "distribution_offset",
                "offset": "offset",
            },
            "parameters": {
                "length": {
                    "default_value": 10,
                    "min_value": 2,
                    "max_value": 200,
                    "description": "ALMA計算期間",
                },
                "sigma": {
                    "default_value": 6.0,
                    "min_value": 0.1,
                    "max_value": 10.0,
                    "description": "ガウス分布のシグマ",
                },
                "distribution_offset": {
                    "default_value": 0.85,
                    "min_value": 0.0,
                    "max_value": 1.0,
                    "description": "ガウス分布のオフセット",
                },
                "offset": {
                    "default_value": 0,
                    "min_value": -10,
                    "max_value": 10,
                    "description": "出力シフト量",
                },
            },
            "pandas_function": "alma",
            "data_column": "Close",
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {
                "length": 10,
                "sigma": 6.0,
                "distribution_offset": 0.85,
                "offset": 0,
            },
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "close > {left_operand}",
                "short": "close < {left_operand}",
            },
            "scale_type": "price_absolute",
            "thresholds": None,
            "type": "trend",
        },
    },
    "BIAS": {
        "config": {
            "result_type": "single",
            "scale_type": "oscillator_plus_minus_100",
            "category": "trend",
            "adapter_function": "app.services.indicators.technical_indicators.trend.TrendIndicators.bias",
            "required_data": ["close"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {
                "close": "data",
                "length": "length",
                "ma_type": "ma_type",
                "offset": "offset",
            },
            "parameters": {
                "length": {
                    "default_value": 26,
                    "min_value": 5,
                    "max_value": 100,
                    "description": "BIAS計算期間",
                },
                "ma_type": {
                    "default_value": "sma",
                    "min_value": None,
                    "max_value": None,
                    "description": "移動平均の種類 (sma, ema, wma, hma, zlma)",
                },
                "offset": {
                    "default_value": 0,
                    "min_value": -10,
                    "max_value": 10,
                    "description": "出力シフト量",
                },
            },
            "pandas_function": "bias",
            "data_column": "Close",
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {"length": 26, "ma_type": "sma", "offset": 0},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "close > {left_operand} * 1.05",
                "short": "close < {left_operand} * 0.95",
            },
            "scale_type": "oscillator_plus_minus_100",
            "thresholds": {"all": {"long_lt": -5, "short_gt": 5}},
            "type": "trend",
        },
    },
    "DEMA": {
        "config": {
            "result_type": "single",
            "scale_type": "price_ratio",
            "category": "trend",
            "adapter_function": "app.services.indicators.technical_indicators.trend.TrendIndicators.dema",
            "required_data": ["close"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {"close": "data", "length": "length"},
            "parameters": {
                "length": {
                    "default_value": 14,
                    "min_value": 2,
                    "max_value": 200,
                    "description": "二重指数移動平均期間",
                }
            },
            "pandas_function": "dema",
            "data_column": "Close",
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {"length": 14},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "close > {left_operand}",
                "short": "close < {left_operand}",
            },
            "scale_type": "price_absolute",
            "thresholds": None,
            "type": "trend",
        },
    },
    "DPO": {
        "config": {
            "result_type": "single",
            "scale_type": "momentum_zero_centered",
            "category": "trend",
            "adapter_function": "app.services.indicators.technical_indicators.trend.TrendIndicators.dpo",
            "required_data": ["close"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {
                "close": "data",
                "length": "length",
                "centered": "centered",
                "offset": "offset",
            },
            "parameters": {
                "length": {
                    "default_value": 20,
                    "min_value": 2,
                    "max_value": 200,
                    "description": "DPO計算期間",
                },
                "centered": {
                    "default_value": True,
                    "min_value": None,
                    "max_value": None,
                    "description": "中心化するかどうか",
                },
                "offset": {
                    "default_value": 0,
                    "min_value": -50,
                    "max_value": 50,
                    "description": "出力オフセット",
                },
            },
            "pandas_function": "dpo",
            "data_column": "Close",
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {"length": 20, "centered": True, "offset": 0},
            "min_length_func": "DPO",
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand} > {threshold}",
                "short": "{left_operand} < {threshold}",
            },
            "scale_type": "momentum_zero_centered",
            "thresholds": {"normal": {"threshold": 0}},
            "type": "trend",
        },
    },
    "FRAMA": {
        "config": {
            "result_type": "single",
            "scale_type": "price_ratio",
            "category": "trend",
            "adapter_function": "app.services.indicators.technical_indicators.original.OriginalIndicators.frama",
            "required_data": ["close"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {"close": "close", "length": "length", "slow": "slow"},
            "parameters": {
                "length": {
                    "default_value": 16,
                    "min_value": 4,
                    "max_value": 200,
                    "description": "FRAMA計算ウィンドウ",
                },
                "slow": {
                    "default_value": 200,
                    "min_value": 1,
                    "max_value": 500,
                    "description": "最大スムージング期間",
                },
            },
            "pandas_function": None,
            "data_column": None,
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {"length": 16, "slow": 200},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "close > {left_operand}",
                "short": "close < {left_operand}",
            },
            "scale_type": "price_absolute",
            "thresholds": None,
            "type": "trend",
        },
    },
    "SUPER_SMOOTHER": {
        "config": {
            "result_type": "single",
            "scale_type": "price_ratio",
            "category": "trend",
            "adapter_function": "app.services.indicators.technical_indicators.original.OriginalIndicators.super_smoother",
            "required_data": ["close"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {"close": "close", "length": "length"},
            "parameters": {
                "length": {
                    "default_value": 10,
                    "min_value": 2,
                    "max_value": 200,
                    "description": "Super Smoother期間",
                }
            },
            "pandas_function": None,
            "data_column": None,
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {"length": 10},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "close > {left_operand}",
                "short": "close < {left_operand}",
            },
            "scale_type": "price_absolute",
            "thresholds": None,
            "type": "trend",
        },
    },
    "EMA": {
        "config": {
            "result_type": "single",
            "scale_type": "price_ratio",
            "category": "trend",
            "adapter_function": "app.services.indicators.technical_indicators.trend.TrendIndicators.ema",
            "required_data": ["close"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {"close": "data", "length": "length"},
            "parameters": {
                "length": {
                    "default_value": 20,
                    "min_value": 2,
                    "max_value": 200,
                    "description": "EMA計算期間",
                }
            },
            "pandas_function": "ema",
            "data_column": "Close",
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {"length": 20},
            "min_length_func": "EMA",
        },
        "yaml": {
            "conditions": {
                "long": "close > {left_operand}",
                "short": "close < {left_operand}",
            },
            "scale_type": "price_absolute",
            "thresholds": "close",
            "type": "trend",
        },
    },
    "HMA": {
        "config": {
            "result_type": "single",
            "scale_type": "price_ratio",
            "category": "trend",
            "adapter_function": "app.services.indicators.technical_indicators.trend.TrendIndicators.hma",
            "required_data": ["close"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {"close": "data", "length": "length"},
            "parameters": {
                "length": {
                    "default_value": 20,
                    "min_value": 2,
                    "max_value": 200,
                    "description": "HMA計算期間",
                }
            },
            "pandas_function": "hma",
            "data_column": "Close",
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {"length": 20},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "close > {left_operand}",
                "short": "close < {left_operand}",
            },
            "scale_type": "price_absolute",
            "thresholds": None,
            "type": "trend",
        },
    },
    "SAR": {
        "config": {
            "result_type": "single",
            "scale_type": "price_absolute",
            "category": "trend",
            "adapter_function": "app.services.indicators.technical_indicators.trend.TrendIndicators.sar",
            "required_data": ["high", "low"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {"high": "high", "low": "low", "af": "af", "max_af": "max_af"},
            "parameters": {
                "af": {
                    "default_value": 0.02,
                    "min_value": 0.01,
                    "max_value": 0.1,
                    "description": "加速因子",
                },
                "max_af": {
                    "default_value": 0.2,
                    "min_value": 0.1,
                    "max_value": 1.0,
                    "description": "最大加速因子",
                },
            },
            "pandas_function": "psar",
            "data_column": None,
            "data_columns": ["High", "Low"],
            "returns": "single",
            "return_cols": None,
            "multi_column": True,
            "default_values": {"af": 0.02, "max_af": 0.2},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "close > {left_operand}",
                "short": "close < {left_operand}",
            },
            "scale_type": "price_absolute",
            "thresholds": None,
            "type": "trend",
        },
    },
    "SMA": {
        "config": {
            "result_type": "single",
            "scale_type": "price_ratio",
            "category": "trend",
            "adapter_function": "app.services.indicators.technical_indicators.trend.TrendIndicators.sma",
            "required_data": ["close"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {"close": "data", "length": "length"},
            "parameters": {
                "length": {
                    "default_value": 20,
                    "min_value": 2,
                    "max_value": 200,
                    "description": "SMA計算期間",
                }
            },
            "pandas_function": "sma",
            "data_column": "Close",
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {"length": 20},
            "min_length_func": "SMA",
        },
        "yaml": {
            "conditions": {
                "long": "close > {left_operand}",
                "short": "close < {left_operand}",
            },
            "scale_type": "price_absolute",
            "thresholds": None,
            "type": "trend",
        },
    },
    "T3": {
        "config": {
            "result_type": "single",
            "scale_type": "price_ratio",
            "category": "trend",
            "adapter_function": "app.services.indicators.technical_indicators.trend.TrendIndicators.t3",
            "required_data": ["close"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {
                "close": "data",
                "length": "length",
                "a": "a",
                "vfactor": "vfactor",
            },
            "parameters": {
                "length": {
                    "default_value": 5,
                    "min_value": 2,
                    "max_value": 50,
                    "description": "T3移動平均期間",
                },
                "a": {
                    "default_value": 0.7,
                    "min_value": 0.1,
                    "max_value": 1.0,
                    "description": "T3スムージングファクター",
                },
                "vfactor": {
                    "default_value": 0.7,
                    "min_value": 0.1,
                    "max_value": 1.0,
                    "description": "pandas-ta互換用パラメータ",
                },
            },
            "pandas_function": "t3",
            "data_column": "Close",
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {"length": 5, "a": 0.7, "vfactor": 0.7},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "close > {left_operand}",
                "short": "close < {left_operand}",
            },
            "scale_type": "price_absolute",
            "thresholds": None,
            "type": "trend",
        },
    },
    "LINREG": {
        "config": {
            "result_type": "single",
            "scale_type": "price_ratio",
            "category": "trend",
            "adapter_function": "app.services.indicators.technical_indicators.trend.TrendIndicators.linreg",
            "required_data": ["close"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {
                "close": "data",
                "length": "length",
                "scalar": "scalar",
                "intercept": "intercept",
            },
            "parameters": {
                "length": {
                    "default_value": 14,
                    "min_value": 2,
                    "max_value": 200,
                    "description": "回帰期間",
                },
                "scalar": {
                    "default_value": 1.0,
                    "min_value": 0.1,
                    "max_value": 10.0,
                    "description": "スケーリング係数",
                },
                "intercept": {
                    "default_value": False,
                    "min_value": None,
                    "max_value": None,
                    "description": "切片を返すかどうか",
                },
            },
            "pandas_function": None,
            "data_column": "Close",
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {"length": 14, "scalar": 1.0, "intercept": False},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "close > {left_operand}",
                "short": "close < {left_operand}",
            },
            "scale_type": "price_absolute",
            "thresholds": None,
            "type": "trend",
        },
    },
    "LINREGSLOPE": {
        "config": {
            "result_type": "single",
            "scale_type": "momentum_zero_centered",
            "category": "trend",
            "adapter_function": "app.services.indicators.technical_indicators.trend.TrendIndicators.linregslope",
            "required_data": ["close"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {"close": "data", "length": "length", "scalar": "scalar"},
            "parameters": {
                "length": {
                    "default_value": 14,
                    "min_value": 2,
                    "max_value": 200,
                    "description": "回帰期間",
                },
                "scalar": {
                    "default_value": 1.0,
                    "min_value": 0.1,
                    "max_value": 10.0,
                    "description": "スケーリング係数",
                },
            },
            "pandas_function": None,
            "data_column": "Close",
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {"length": 14, "scalar": 1.0},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {"long": "{left_operand} > 0", "short": "{left_operand} < 0"},
            "scale_type": "momentum_zero_centered",
            "thresholds": {"zero_cross": True},
            "type": "trend",
        },
    },
    "TRIMA": {
        "config": {
            "result_type": "single",
            "scale_type": "price_ratio",
            "category": "trend",
            "adapter_function": "app.services.indicators.technical_indicators.trend.TrendIndicators.trima",
            "required_data": ["close"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {"close": "data", "length": "length", "talib": "talib"},
            "parameters": {
                "length": {
                    "default_value": 10,
                    "min_value": 2,
                    "max_value": 200,
                    "description": "TRIMA期間",
                }
            },
            "pandas_function": "trima",
            "data_column": "Close",
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {"length": 10},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "close > {left_operand}",
                "short": "close < {left_operand}",
            },
            "scale_type": "price_absolute",
            "thresholds": None,
            "type": "trend",
        },
    },
    "TEMA": {
        "config": {
            "result_type": "single",
            "scale_type": "price_ratio",
            "category": "trend",
            "adapter_function": "app.services.indicators.technical_indicators.trend.TrendIndicators.tema",
            "required_data": ["close"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {"close": "data", "length": "length"},
            "parameters": {
                "length": {
                    "default_value": 14,
                    "min_value": 2,
                    "max_value": 200,
                    "description": "三重指数移動平均期間",
                }
            },
            "pandas_function": "tema",
            "data_column": "Close",
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {"length": 14},
            "min_length_func": "TEMA",
        },
        "yaml": {
            "conditions": {
                "long": "close > {left_operand}",
                "short": "close < {left_operand}",
            },
            "scale_type": "price_absolute",
            "thresholds": None,
            "type": "trend",
        },
    },
    "VWMA": {
        "config": {
            "result_type": "single",
            "scale_type": "price_ratio",
            "category": "trend",
            "adapter_function": "app.services.indicators.technical_indicators.trend.TrendIndicators.vwma",
            "required_data": ["close", "volume"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {"volume": "volume", "length": "length"},
            "parameters": {
                "length": {
                    "default_value": 20,
                    "min_value": 2,
                    "max_value": 200,
                    "description": "VWMA期間",
                }
            },
            "pandas_function": "vwma",
            "data_column": "Close",
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {"length": 20},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "close > {left_operand}",
                "short": "close < {left_operand}",
            },
            "scale_type": "price_absolute",
            "thresholds": None,
            "type": "trend",
        },
    },
    "ZLMA": {
        "config": {
            "result_type": "single",
            "scale_type": "price_ratio",
            "category": "trend",
            "adapter_function": "app.services.indicators.technical_indicators.trend.TrendIndicators.zlma",
            "required_data": ["close"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {
                "close": "data",
                "length": "length",
                "mamode": "mamode",
                "offset": "offset",
            },
            "parameters": {
                "length": {
                    "default_value": 10,
                    "min_value": 2,
                    "max_value": 200,
                    "description": "ZLMA期間",
                },
                "mamode": {
                    "default_value": "ema",
                    "min_value": None,
                    "max_value": None,
                    "description": "元となる移動平均モード",
                },
                "offset": {
                    "default_value": 0,
                    "min_value": -10,
                    "max_value": 10,
                    "description": "シフト量",
                },
            },
            "pandas_function": "zlma",
            "data_column": "Close",
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {"length": 10, "mamode": "ema", "offset": 0},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "close > {left_operand}",
                "short": "close < {left_operand}",
            },
            "scale_type": "price_absolute",
            "thresholds": None,
            "type": "trend",
        },
    },
    "VORTEX": {
        "config": {
            "result_type": "complex",
            "scale_type": "price_ratio",
            "category": "trend",
            "adapter_function": "app.services.indicators.technical_indicators.trend.TrendIndicators.vortex",
            "required_data": ["high", "low", "close"],
            "output_names": ["VORTEX_Positive", "VORTEX_Negative"],
            "default_output": "VORTEX_Positive",
            "aliases": None,
            "param_map": {
                "high": "high",
                "low": "low",
                "close": "close",
                "length": "length",
                "drift": "drift",
                "offset": "offset",
            },
            "parameters": {
                "length": {
                    "default_value": 14,
                    "min_value": 2,
                    "max_value": 200,
                    "description": "Vortex期間",
                },
                "drift": {
                    "default_value": 1,
                    "min_value": 1,
                    "max_value": 10,
                    "description": "差分に使用するドリフト",
                },
                "offset": {
                    "default_value": 0,
                    "min_value": -10,
                    "max_value": 10,
                    "description": "出力オフセット",
                },
            },
            "pandas_function": "vortex",
            "data_column": None,
            "data_columns": ["High", "Low", "Close"],
            "returns": "multiple",
            "return_cols": ["VTXP", "VTXM"],
            "multi_column": True,
            "default_values": {"length": 14, "drift": 1, "offset": 0},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand}_0 > {left_operand}_1",
                "short": "{left_operand}_0 < {left_operand}_1",
            },
            "scale_type": "price_ratio",
            "thresholds": None,
            "type": "trend",
        },
    },
    "WMA": {
        "config": {
            "result_type": "single",
            "scale_type": "price_ratio",
            "category": "trend",
            "adapter_function": "app.services.indicators.technical_indicators.trend.TrendIndicators.wma",
            "required_data": ["close"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {"close": "data", "length": "length"},
            "parameters": {
                "length": {
                    "default_value": 20,
                    "min_value": 2,
                    "max_value": 200,
                    "description": None,
                }
            },
            "pandas_function": "wma",
            "data_column": "Close",
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {"length": 20},
            "min_length_func": "WMA",
        },
        "yaml": {
            "conditions": {
                "long": "close > {left_operand}",
                "short": "close < {left_operand}",
            },
            "scale_type": "price_absolute",
            "thresholds": None,
            "type": "trend",
        },
    },
    "AMAT": {
        "config": {
            "result_type": "single",
            "scale_type": "price_ratio",
            "category": "trend",
            "adapter_function": "app.services.indicators.technical_indicators.trend.TrendIndicators.amat",
            "required_data": ["close"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {
                "close": "data",
                "fast": "fast",
                "slow": "slow",
                "signal": "signal",
            },
            "parameters": {
                "fast": {
                    "default_value": 3,
                    "min_value": 2,
                    "max_value": 20,
                    "description": "AMAT短期期間",
                },
                "slow": {
                    "default_value": 30,
                    "min_value": 10,
                    "max_value": 50,
                    "description": "AMAT長期期間",
                },
                "signal": {
                    "default_value": 10,
                    "min_value": 5,
                    "max_value": 30,
                    "description": "シグナル期間",
                },
            },
            "pandas_function": "amat",
            "data_column": "Close",
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {"fast": 3, "slow": 30, "signal": 10},
            "min_length_func": None,
            # パラメータ依存関係制約: fast期間 < slow期間
            "parameter_constraints": [
                {"type": "less_than", "param1": "fast", "param2": "slow"},
            ],
        },
        "yaml": {
            "conditions": {
                "long": "close > {left_operand}",
                "short": "close < {left_operand}",
            },
            "scale_type": "price_absolute",
            "thresholds": None,
            "type": "trend",
        },
    },
    "AROON": {
        "config": {
            "result_type": "complex",
            "scale_type": "oscillator_0_100",
            "category": "trend",
            "adapter_function": "app.services.indicators.technical_indicators.trend.TrendIndicators.aroon",
            "required_data": ["high", "low"],
            "output_names": ["AROON_UP", "AROON_DOWN", "AROON_OSC"],
            "default_output": "AROON_OSC",
            "aliases": None,
            "param_map": {"length": "length"},
            "parameters": {
                "length": {
                    "default_value": 14,
                    "min_value": 2,
                    "max_value": 100,
                    "description": "Aroon計算期間",
                }
            },
            "pandas_function": "aroon",
            "data_column": None,
            "data_columns": ["High", "Low"],
            "returns": "multiple",
            "return_cols": ["AROOND", "AROONU", "AROONOSC"],
            "multi_column": True,
            "default_values": {"length": 14},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand}_osc > {threshold}",
                "short": "{left_operand}_osc < -{threshold}",
            },
            "scale_type": "oscillator_0_100",
            "thresholds": {
                "aggressive": {"trend_min": 50},
                "conservative": {"trend_min": 80},
                "normal": {"trend_min": 70},
            },
            "type": "trend",
        },
    },
    "RMA": {
        "config": {
            "result_type": "single",
            "scale_type": "price_ratio",
            "category": "trend",
            "adapter_function": "app.services.indicators.technical_indicators.trend.TrendIndicators.rma",
            "required_data": ["close"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {"close": "data", "length": "length"},
            "parameters": {
                "length": {
                    "default_value": 10,
                    "min_value": 2,
                    "max_value": 50,
                    "description": "RMA期間",
                }
            },
            "pandas_function": "rma",
            "data_column": "Close",
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {"length": 10},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "close > {left_operand}",
                "short": "close < {left_operand}",
            },
            "scale_type": "price_absolute",
            "thresholds": None,
            "type": "trend",
        },
    },
}
