from __future__ import annotations

from typing import Any, Dict

MANIFEST_VOLATILITY: Dict[str, Dict[str, Any]] = {
    "ACCBANDS": {
        "config": {
            "result_type": "complex",
            "scale_type": "price_absolute",
            "category": "volatility",
            "adapter_function": "app.services.indicators.technical_indicators.volatility.VolatilityIndicators.accbands",
            "required_data": ["high", "low", "close"],
            "output_names": ["ACCBANDS_Upper", "ACCBANDS_Middle", "ACCBANDS_Lower"],
            "default_output": "ACCBANDS_Middle",
            "aliases": None,
            "param_map": {"length": "length"},
            "parameters": {},
            "pandas_function": None,
            "data_column": None,
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "close > {left_operand}_lower",
                "short": "close < {left_operand}_upper",
            },
            "scale_type": "price_absolute",
            "thresholds": {
                "aggressive": {"acceleration": 0.005},
                "conservative": {"acceleration": 0.02},
                "normal": {"acceleration": 0.01},
            },
            "type": "volatility",
        },
    },
    "ATR": {
        "config": {
            "result_type": "single",
            "scale_type": "price_absolute",
            "category": "volatility",
            "adapter_function": "app.services.indicators.technical_indicators.volatility.VolatilityIndicators.atr",
            "required_data": ["high", "low", "close"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {
                "high": "high",
                "low": "low",
                "close": "close",
                "length": "length",
            },
            "parameters": {
                "length": {
                    "default_value": 14,
                    "min_value": 2,
                    "max_value": 100,
                    "description": "ATR計算期間",
                }
            },
            "pandas_function": "atr",
            "data_column": None,
            "data_columns": ["High", "Low", "Close"],
            "returns": "single",
            "return_cols": None,
            "multi_column": True,
            "default_values": {"length": 14},
            "min_length_func": None,
            "absolute_min_length": 3,
        },
        "yaml": {
            "conditions": {
                "long": "close > {left_operand}_current + {multiplier}",
                "short": "close < {left_operand}_current - {multiplier}",
            },
            "scale_type": "price_absolute",
            "thresholds": {
                "aggressive": {"multiplier": 0.5},
                "conservative": {"multiplier": 1.5},
                "normal": {"multiplier": 1.0},
            },
            "type": "volatility",
        },
    },
    "BB": {
        "config": {
            "result_type": "complex",
            "scale_type": "price_ratio",
            "category": "volatility",
            "adapter_function": "app.services.indicators.technical_indicators.volatility.VolatilityIndicators.bbands",
            "required_data": ["close"],
            "output_names": ["BB_Upper", "BB_Middle", "BB_Lower"],
            "default_output": "BB_Middle",
            "aliases": None,
            "param_map": {"close": "data", "length": "length", "std": "std"},
            "parameters": {
                "length": {
                    "default_value": 20,
                    "min_value": 5,
                    "max_value": 100,
                    "description": "ボリンジャーバンド期間",
                },
                "std": {
                    "default_value": 2.0,
                    "min_value": 0.5,
                    "max_value": 5.0,
                    "description": "標準偏差倍数",
                },
            },
            "pandas_function": "bbands",
            "data_column": "Close",
            "data_columns": None,
            "returns": "multiple",
            "return_cols": ["BBL", "BBM", "BBU"],
            "multi_column": False,
            "default_values": {"length": 20, "std": 2.0},
            "min_length_func": "BB",
            "absolute_min_length": 3,
        },
        "yaml": {
            "components": ["upper", "middle", "lower"],
            "conditions": {
                "long": "close < {left_operand}_lower",
                "short": "close > {left_operand}_upper",
            },
            "scale_type": "price_absolute",
            "thresholds": None,
            "type": "volatility",
        },
    },
    "CHOP": {
        "config": {
            "result_type": "single",
            "scale_type": "oscillator_0_100",
            "category": "volatility",
            "adapter_function": "app.services.indicators.technical_indicators.trend.TrendIndicators.chop",
            "required_data": ["high", "low", "close"],
            "output_names": None,
            "default_output": None,
            "aliases": ["Choppiness_Index"],
            "param_map": {
                "high": "high",
                "low": "low",
                "close": "close",
                "length": "length",
                "drift": "drift",
                "offset": "offset",
            },
            "parameters": {
                "length": {
                    "default_value": 14,
                    "min_value": 2,
                    "max_value": 100,
                    "description": "CHOP計算期間",
                },
                "drift": {
                    "default_value": 1,
                    "min_value": 1,
                    "max_value": 10,
                    "description": "ドリフト",
                },
                "offset": {
                    "default_value": 0,
                    "min_value": -10,
                    "max_value": 10,
                    "description": "出力オフセット",
                },
            },
            "pandas_function": "chop",
            "data_column": "Close",
            "data_columns": ["High", "Low", "Close"],
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {"length": 14, "drift": 1, "offset": 0},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand} < 38.2",
                "short": "{left_operand} > 61.8",
            },
            "scale_type": "oscillator_0_100",
            "thresholds": {
                "aggressive": {"long_lt": 45, "short_gt": 55},
                "conservative": {"long_lt": 35, "short_gt": 65},
                "normal": {"long_lt": 38.2, "short_gt": 61.8},
            },
            "type": "volatility",
        },
    },
    "DONCHIAN": {
        "config": {
            "result_type": "complex",
            "scale_type": "price_absolute",
            "category": "volatility",
            "adapter_function": "app.services.indicators.technical_indicators.volatility.VolatilityIndicators.donchian",
            "required_data": ["high", "low", "close"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {
                "high": "high",
                "low": "low",
                "close": "close",
                "length": "length",
            },
            "parameters": {
                "length": {
                    "default_value": 20,
                    "min_value": 2,
                    "max_value": 200,
                    "description": "Donchian Channels期間",
                }
            },
            "pandas_function": "donchian",
            "data_column": None,
            "data_columns": ["High", "Low", "Close"],
            "returns": "multiple",
            "return_cols": ["DC_LB", "DC_MB", "DC_UB"],
            "multi_column": True,
            "default_values": {"length": 20},
            "min_length_func": None,
            "absolute_min_length": 2,
        },
        "yaml": {
            "conditions": {
                "long": "close > {left_operand}_mid",
                "short": "close < {left_operand}_mid",
            },
            "scale_type": "price_absolute",
            "thresholds": {
                "aggressive": {"period": 10},
                "combo": {
                    "condition": "(close - lower) / (upper - lower) >= primary or (close - lower) / (upper - lower) <= secondary",
                    "primary": 0.9,
                    "secondary": 0.1,
                },
                "conservative": {"period": 30},
                "normal": {"period": 20},
                "range": {"break_out_threshold": 0.8, "consolidation_threshold": 0.3},
            },
            "type": "volatility",
        },
    },
    "KELTNER": {
        "config": {
            "result_type": "complex",
            "scale_type": "price_ratio",
            "category": "volatility",
            "adapter_function": "app.services.indicators.technical_indicators.volatility.VolatilityIndicators.keltner",
            "required_data": ["high", "low", "close"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {
                "high": "high",
                "low": "low",
                "close": "close",
                "length": "length",
                "multiplier": "multiplier",
            },
            "parameters": {
                "length": {
                    "default_value": 20,
                    "min_value": 2,
                    "max_value": 100,
                    "description": "Keltner Channels期間",
                },
                "multiplier": {
                    "default_value": 2.0,
                    "min_value": 0.5,
                    "max_value": 5.0,
                    "description": "ATR倍数",
                },
            },
            "pandas_function": "kc",
            "data_column": None,
            "data_columns": ["High", "Low", "Close"],
            "returns": "multiple",
            "return_cols": ["KC_LB", "KC_MID", "KC_UB"],
            "multi_column": True,
            "default_values": {"length": 20, "multiplier": 2.0},
            "min_length_func": None,
            "absolute_min_length": 5,
        },
        "yaml": {
            "conditions": {
                "long": "close > {left_operand}_upper",
                "short": "close < {left_operand}_lower",
            },
            "scale_type": "price_absolute",
            "thresholds": {
                "aggressive": {"multiplier": 1.0},
                "combo": {
                    "condition": "distance >= primary or distance <= secondary",
                    "primary": 2.5,
                    "secondary": -2.5,
                },
                "conservative": {"multiplier": 2.0},
                "normal": {"multiplier": 1.5},
                "range": {"break_out_lower": -1.8, "break_out_upper": 1.8},
            },
            "type": "volatility",
        },
    },
    "RVI": {
        "config": {
            "result_type": "single",
            "scale_type": "oscillator_0_100",
            "category": "volatility",
            "adapter_function": "app.services.indicators.technical_indicators.volatility.VolatilityIndicators.rvi",
            "required_data": ["close", "high", "low"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {
                "close": "close",
                "high": "high",
                "low": "low",
                "length": "length",
                "scalar": "scalar",
                "refined": "refined",
                "thirds": "thirds",
                "mamode": "mamode",
                "drift": "drift",
                "offset": "offset",
            },
            "parameters": {
                "length": {
                    "default_value": 14,
                    "min_value": 2,
                    "max_value": 200,
                    "description": "RVI計算期間",
                },
                "scalar": {
                    "default_value": 100.0,
                    "min_value": 1.0,
                    "max_value": 200.0,
                    "description": "指数スケール係数",
                },
                "refined": {
                    "default_value": False,
                    "min_value": None,
                    "max_value": None,
                    "description": "Refined モードを使用",
                },
                "thirds": {
                    "default_value": False,
                    "min_value": None,
                    "max_value": None,
                    "description": "Thirds モードを使用",
                },
                "mamode": {
                    "default_value": "ema",
                    "min_value": None,
                    "max_value": None,
                    "description": "平滑化移動平均モード",
                },
                "drift": {
                    "default_value": 1,
                    "min_value": 1,
                    "max_value": 10,
                    "description": "差分に使用するドリフト",
                },
                "offset": {
                    "default_value": 0,
                    "min_value": -10,
                    "max_value": 10,
                    "description": "出力オフセット",
                },
            },
            "pandas_function": "rvi",
            "data_column": None,
            "data_columns": ["Close", "High", "Low"],
            "returns": "single",
            "return_cols": None,
            "multi_column": True,
            "default_values": {
                "length": 14,
                "scalar": 100.0,
                "refined": False,
                "thirds": False,
                "mamode": "ema",
                "drift": 1,
                "offset": 0,
            },
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand} > {threshold}",
                "short": "{left_operand} < {threshold}",
            },
            "scale_type": "oscillator_0_100",
            "thresholds": {
                "aggressive": {"long_gt": 55, "short_lt": 45},
                "normal": {"long_gt": 60, "short_lt": 40},
                "conservative": {"long_gt": 65, "short_lt": 35},
            },
            "type": "volatility",
        },
    },
    "SUPERTREND": {
        "config": {
            "result_type": "complex",
            "scale_type": "price_absolute",
            "category": "volatility",
            "adapter_function": "app.services.indicators.technical_indicators.volatility.VolatilityIndicators.supertrend",
            "required_data": ["high", "low", "close"],
            "output_names": [
                "SUPERTREND_Lower",
                "SUPERTREND_Upper",
                "SUPERTREND_Direction",
            ],
            "default_output": "SUPERTREND_Direction",
            "aliases": None,
            "param_map": {
                "high": "high",
                "low": "low",
                "close": "close",
                "length": "length",
                "multiplier": "multiplier",
            },
            "parameters": {
                "length": {
                    "default_value": 10,
                    "min_value": 2,
                    "max_value": 200,
                    "description": "ATR期間",
                },
                "multiplier": {
                    "default_value": 3.0,
                    "min_value": 1.0,
                    "max_value": 10.0,
                    "description": "ATR倍数",
                },
            },
            "pandas_function": "supertrend",
            "data_column": None,
            "data_columns": ["High", "Low", "Close"],
            "returns": "complex",
            "return_cols": ["ST", "D"],
            "multi_column": True,
            "default_values": {"length": 10, "multiplier": 3.0},
            "min_length_func": "SUPERTREND",
            "absolute_min_length": 5,
        },
        "yaml": {
            "components": ["lower", "upper", "direction"],
            "conditions": {
                "long": "{left_operand}_2 > 0",
                "short": "{left_operand}_2 < 0",
            },
            "scale_type": "price_absolute",
            "thresholds": {
                "aggressive": {"multiplier": 1.5},
                "conservative": {"multiplier": 4.5},
                "normal": {"multiplier": 3.0},
            },
            "type": "volatility",
        },
    },
    "NATR": {
        "config": {
            "result_type": "single",
            "scale_type": "momentum_zero_centered",
            "category": "volatility",
            "adapter_function": "app.services.indicators.technical_indicators.volatility.VolatilityIndicators.natr",
            "required_data": ["high", "low", "close"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {
                "high": "high",
                "low": "low",
                "close": "close",
                "length": "length",
            },
            "parameters": {
                "length": {
                    "default_value": 14,
                    "min_value": 2,
                    "max_value": 200,
                    "description": "NATR計算期間",
                }
            },
            "pandas_function": "natr",
            "data_column": None,
            "data_columns": ["High", "Low", "Close"],
            "returns": "single",
            "return_cols": None,
            "multi_column": True,
            "default_values": {"length": 14},
            "min_length_func": None,
            "absolute_min_length": 3,
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand} < {threshold}",
                "short": "{left_operand} > {threshold}",
            },
            "scale_type": "momentum_zero_centered",
            "thresholds": {
                "aggressive": {"long_lt": 1.5, "short_gt": 5.0},
                "normal": {"long_lt": 2.0, "short_gt": 4.0},
                "conservative": {"long_lt": 2.5, "short_gt": 3.5},
            },
            "type": "volatility",
        },
    },
    "UI": {
        "config": {
            "result_type": "single",
            "scale_type": "oscillator_0_100",
            "category": "volatility",
            "adapter_function": "app.services.indicators.technical_indicators.volatility.VolatilityIndicators.ui",
            "required_data": ["close"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {"close": "data", "length": "length"},
            "parameters": {
                "length": {
                    "default_value": 14,
                    "min_value": 2,
                    "max_value": 100,
                    "description": "UI計算期間",
                }
            },
            "pandas_function": None,
            "data_column": None,
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {"length": 14},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand} < {threshold}",
                "short": "{left_operand} > {threshold}",
            },
            "scale_type": "oscillator_0_100",
            "thresholds": {"all": {"long_lt": 30, "short_gt": 70}},
            "type": "volatility",
        },
    },
    "VHF": {
        "config": {
            "result_type": "single",
            "scale_type": "oscillator_0_100",
            "category": "volatility",
            "adapter_function": "app.services.indicators.technical_indicators.volatility.VolatilityIndicators.vhf",
            "required_data": ["close"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {
                "length": "length",
                "scalar": "scalar",
                "drift": "drift",
                "offset": "offset",
            },
            "parameters": {
                "length": {
                    "default_value": 28,
                    "min_value": 10,
                    "max_value": 100,
                    "description": "VHF期間",
                },
                "scalar": {
                    "default_value": 100.0,
                    "min_value": 1.0,
                    "max_value": 1000.0,
                    "description": "VHFスカラー",
                },
                "drift": {
                    "default_value": 1,
                    "min_value": 1,
                    "max_value": 10,
                    "description": "ドリフト期間",
                },
                "offset": {
                    "default_value": 0,
                    "min_value": 0,
                    "max_value": 10,
                    "description": "オフセット",
                },
            },
            "pandas_function": "vhf",
            "data_column": "Close",
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {"length": 28, "scalar": 100.0, "drift": 1, "offset": 0},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "close > {left_operand}",
                "short": "close < {left_operand}",
            },
            "scale_type": "oscillator_0_100",
            "thresholds": {"all": {"long_lt": 0.3, "short_gt": 0.7}},
            "type": "volatility",
        },
    },
    "GRI": {
        "config": {
            "result_type": "single",
            "scale_type": "momentum_zero_centered",
            "category": "volatility",
            "adapter_function": "app.services.indicators.technical_indicators.volatility.VolatilityIndicators.gri",
            "required_data": ["high", "low", "close"],
            "output_names": None,
            "default_output": None,
            "aliases": ["gopalakrishnan_range"],
            "param_map": {
                "high": "high",
                "low": "low",
                "close": "close",
                "length": "length",
                "offset": "offset",
            },
            "parameters": {
                "length": {
                    "default_value": 14,
                    "min_value": 2,
                    "max_value": 100,
                    "description": "GRI計算期間",
                },
                "offset": {
                    "default_value": 0,
                    "min_value": -10,
                    "max_value": 10,
                    "description": "出力オフセット",
                },
            },
            "pandas_function": "kvo",
            "data_column": None,
            "data_columns": ["High", "Low", "Close"],
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {"length": 14, "offset": 0},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand} > {threshold}",
                "short": "left_operand} < {threshold}",
            },
            "scale_type": "momentum_zero_centered",
            "thresholds": {
                "aggressive": {"long_gt": 10, "short_lt": -10},
                "conservative": {"long_gt": 30, "short_lt": -30},
                "normal": {"long_gt": 20, "short_lt": -20},
            },
            "type": "volatility",
        },
    },
    "PARKINSON": {
        "config": {
            "result_type": "single",
            "scale_type": "price_absolute",
            "category": "volatility",
            "adapter_function": "app.services.indicators.technical_indicators.volatility.VolatilityIndicators.parkinson",
            "required_data": ["high", "low"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {"high": "high", "low": "low", "length": "length"},
            "parameters": {
                "length": {
                    "default_value": 20,
                    "min_value": 2,
                    "max_value": 200,
                    "description": "Parkinson volatility period",
                }
            },
            "pandas_function": None,
            "data_column": None,
            "data_columns": ["High", "Low"],
            "returns": "single",
            "return_cols": None,
            "multi_column": True,
            "default_values": {"length": 20},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {},
            "scale_type": "price_absolute",
            "thresholds": None,
            "type": "volatility",
        },
    },
    "GARMAN_KLASS": {
        "config": {
            "result_type": "single",
            "scale_type": "price_absolute",
            "category": "volatility",
            "adapter_function": "app.services.indicators.technical_indicators.volatility.VolatilityIndicators.garman_klass",
            "required_data": ["open", "high", "low", "close"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {
                "open": "open_",
                "high": "high",
                "low": "low",
                "close": "close",
                "length": "length",
            },
            "parameters": {
                "length": {
                    "default_value": 20,
                    "min_value": 2,
                    "max_value": 200,
                    "description": "Garman-Klass volatility period",
                }
            },
            "pandas_function": None,
            "data_column": None,
            "data_columns": ["Open", "High", "Low", "Close"],
            "returns": "single",
            "return_cols": None,
            "multi_column": True,
            "default_values": {"length": 20},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {},
            "scale_type": "price_absolute",
            "thresholds": None,
            "type": "volatility",
        },
    },
}
