from __future__ import annotations

from typing import Any, Dict

MANIFEST_VOLUME: Dict[str, Dict[str, Any]] = {
    "AD": {
        "config": {
            "result_type": "single",
            "scale_type": "volume",
            "category": "volume",
            "adapter_function": "app.services.indicators.technical_indicators.volume.VolumeIndicators.ad",
            "required_data": ["high", "low", "close", "volume"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {},
            "parameters": {},
            "pandas_function": None,
            "data_column": None,
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {},
            "min_length_func": None,
            "absolute_min_length": 2,
        },
        "yaml": {
            "conditions": {
                "long": "close > {left_operand}",
                "short": "close < {left_operand}",
            },
            "scale_type": "price_absolute",
            "thresholds": None,
            "type": "volume",
        },
    },
    "ADOSC": {
        "config": {
            "result_type": "single",
            "scale_type": "volume",
            "category": "volume",
            "adapter_function": "app.services.indicators.technical_indicators.volume.VolumeIndicators.adosc",
            "required_data": ["high", "low", "close", "volume"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {"fast": "fast", "slow": "slow"},
            "parameters": {
                "fast": {
                    "default_value": 3,
                    "min_value": 1,
                    "max_value": 20,
                    "description": None,
                },
                "slow": {
                    "default_value": 10,
                    "min_value": 2,
                    "max_value": 40,
                    "description": None,
                },
            },
            "pandas_function": None,
            "data_column": None,
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {"fast": 3, "slow": 10},
            "min_length_func": None,
            # パラメータ依存関係制約: fast期間 < slow期間
            "parameter_constraints": [
                {"type": "less_than", "param1": "fast", "param2": "slow"},
            ],
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand} > {threshold}",
                "short": "{left_operand} < {threshold}",
            },
            "scale_type": "momentum_zero_centered",
            "thresholds": {
                "aggressive": {"long_gt": -10000, "short_lt": 10000},
                "conservative": {"long_gt": -2000, "short_lt": 2000},
                "normal": {"long_gt": -5000, "short_lt": 5000},
            },
            "type": "volume",
        },
    },
    "CMF": {
        "config": {
            "result_type": "single",
            "scale_type": "price_absolute",
            "category": "volume",
            "adapter_function": "app.services.indicators.technical_indicators.volume.VolumeIndicators.cmf",
            "required_data": ["high", "low", "close", "volume"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {"length": "length"},
            "parameters": {
                "length": {
                    "default_value": 20,
                    "min_value": 2,
                    "max_value": 100,
                    "description": None,
                }
            },
            "pandas_function": None,
            "data_column": None,
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {"length": 20},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "close > {left_operand}_mid",
                "short": "close < {left_operand}_mid",
            },
            "scale_type": "price_absolute",
            "thresholds": {
                "aggressive": {"multiplier": 1.5},
                "conservative": {"multiplier": 2.5},
                "normal": {"multiplier": 2.0},
            },
            "type": "volume",
        },
    },
    "EFI": {
        "config": {
            "result_type": "single",
            "scale_type": "momentum_zero_centered",
            "category": "volume",
            "adapter_function": "app.services.indicators.technical_indicators.volume.VolumeIndicators.efi",
            "required_data": ["close", "volume"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {"length": "length"},
            "parameters": {
                "length": {
                    "default_value": 13,
                    "min_value": 2,
                    "max_value": 200,
                    "description": None,
                }
            },
            "pandas_function": None,
            "data_column": None,
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {"length": 13},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand} > {threshold}",
                "short": "{left_operand} < {threshold}",
            },
            "scale_type": "momentum_zero_centered",
            "thresholds": {"all": {"long_gt": 0, "short_lt": 0}},
            "type": "volume",
        },
    },
    "EOM": {
        "config": {
            "result_type": "single",
            "scale_type": "momentum_zero_centered",
            "category": "volume",
            "adapter_function": "app.services.indicators.technical_indicators.volume.VolumeIndicators.eom",
            "required_data": ["high", "low", "close", "volume"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {
                "length": "length",
                "divisor": "divisor",
                "drift": "drift",
                "offset": "offset",
            },
            "parameters": {
                "length": {
                    "default_value": 14,
                    "min_value": 2,
                    "max_value": 200,
                    "description": "EOM計算期間",
                },
                "divisor": {
                    "default_value": 100000000.0,
                    "min_value": None,
                    "max_value": None,
                    "description": "正規化に使用する除数",
                },
                "drift": {
                    "default_value": 1,
                    "min_value": 1,
                    "max_value": 10,
                    "description": "変化を測るドリフト",
                },
                "offset": {
                    "default_value": 0,
                    "min_value": -10,
                    "max_value": 10,
                    "description": "出力オフセット",
                },
            },
            "pandas_function": "eom",
            "data_column": None,
            "data_columns": ["High", "Low", "Close", "Volume"],
            "returns": "single",
            "return_cols": None,
            "multi_column": True,
            "default_values": {
                "length": 14,
                "divisor": 100000000.0,
                "drift": 1,
                "offset": 0,
            },
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand} > {threshold}",
                "short": "{left_operand} < {threshold}",
            },
            "scale_type": "momentum_zero_centered",
            "thresholds": {"normal": {"threshold": 0}},
            "type": "volume",
        },
    },
    "MFI": {
        "config": {
            "result_type": "single",
            "scale_type": "oscillator_0_100",
            "category": "volume",
            "adapter_function": "app.services.indicators.technical_indicators.volume.VolumeIndicators.mfi",
            "required_data": ["high", "low", "close", "volume"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {"length": "length"},
            "parameters": {
                "length": {
                    "default_value": 14,
                    "min_value": 2,
                    "max_value": 100,
                    "description": "MFI計算期間",
                }
            },
            "pandas_function": None,
            "data_column": None,
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {"length": 14},
            "min_length_func": None,
            "absolute_min_length": 3,
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand} < {threshold}",
                "short": "{left_operand} > {threshold}",
            },
            "scale_type": "oscillator_0_100",
            "thresholds": {
                "aggressive": {"long_lt": 20, "short_gt": 85},
                "conservative": {"long_lt": 40, "short_gt": 60},
                "normal": {"long_lt": 30, "short_gt": 70},
            },
            "type": "volume",
        },
    },
    "OBV": {
        "config": {
            "result_type": "single",
            "scale_type": "momentum_zero_centered",
            "category": "volume",
            "adapter_function": "app.services.indicators.technical_indicators.volume.VolumeIndicators.obv",
            "required_data": ["close", "volume"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {},
            "parameters": {},
            "pandas_function": None,
            "data_column": None,
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {},
            "min_length_func": None,
            "absolute_min_length": 2,
        },
        "yaml": {
            "conditions": {"long": "{left_operand} > 0", "short": "{left_operand} < 0"},
            "scale_type": "momentum_zero_centered",
            "thresholds": {"zero_cross": True},
            "type": "volume",
        },
    },
    "KVO": {
        "config": {
            "result_type": "complex",
            "scale_type": "momentum_zero_centered",
            "category": "volume",
            "adapter_function": "app.services.indicators.technical_indicators.volume.VolumeIndicators.kvo",
            "required_data": ["high", "low", "close", "volume"],
            "output_names": ["KVO", "KVO_SIGNAL"],
            "default_output": "KVO",
            "aliases": None,
            "param_map": {
                "high": "high",
                "low": "low",
                "close": "close",
                "volume": "volume",
                "fast": "fast",
                "slow": "slow",
                "signal": "signal",
                "scalar": "scalar",
                "mamode": "mamode",
                "drift": "drift",
            },
            "parameters": {
                "fast": {
                    "default_value": 34,
                    "min_value": 2,
                    "max_value": 100,
                    "description": "短期EMA期間",
                },
                "slow": {
                    "default_value": 55,
                    "min_value": 5,
                    "max_value": 200,
                    "description": "長期EMA期間",
                },
                "signal": {
                    "default_value": 13,
                    "min_value": 1,
                    "max_value": 100,
                    "description": "シグナルEMA期間",
                },
                "scalar": {
                    "default_value": 100.0,
                    "min_value": 1.0,
                    "max_value": 200.0,
                    "description": "スケール係数",
                },
                "mamode": {
                    "default_value": "ema",
                    "min_value": None,
                    "max_value": None,
                    "description": "平滑化モード",
                },
                "drift": {
                    "default_value": 1,
                    "min_value": 1,
                    "max_value": 10,
                    "description": "差分に用いるドリフト",
                },
            },
            "pandas_function": "kvo",
            "data_column": None,
            "data_columns": ["High", "Low", "Close", "Volume"],
            "returns": "multiple",
            "return_cols": ["KVO", "KVOs"],
            "multi_column": True,
            "default_values": {
                "fast": 34,
                "slow": 55,
                "signal": 13,
                "scalar": 100.0,
                "mamode": "ema",
                "drift": 1,
            },
            "min_length_func": None,
            # パラメータ依存関係制約: fast期間 < slow期間
            "parameter_constraints": [
                {"type": "less_than", "param1": "fast", "param2": "slow"},
            ],
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand}_0 > 0",
                "short": "{left_operand}_0 < 0",
            },
            "scale_type": "momentum_zero_centered",
            "thresholds": {"zero_cross": True},
            "type": "volume",
        },
    },
    "PVO": {
        "config": {
            "result_type": "complex",
            "scale_type": "momentum_zero_centered",
            "category": "volume",
            "adapter_function": "app.services.indicators.technical_indicators.volume.VolumeIndicators.pvo",
            "required_data": ["volume"],
            "output_names": ["PVO", "PVO_SIGNAL", "PVO_HIST"],
            "default_output": "PVO",
            "aliases": None,
            "param_map": {
                "volume": "volume",
                "fast": "fast",
                "slow": "slow",
                "signal": "signal",
                "scalar": "scalar",
            },
            "parameters": {
                "fast": {
                    "default_value": 12,
                    "min_value": 1,
                    "max_value": 200,
                    "description": "高速EMA期間",
                },
                "slow": {
                    "default_value": 26,
                    "min_value": 2,
                    "max_value": 300,
                    "description": "低速EMA期間",
                },
                "signal": {
                    "default_value": 9,
                    "min_value": 1,
                    "max_value": 200,
                    "description": "シグナル期間",
                },
                "scalar": {
                    "default_value": 100.0,
                    "min_value": 1.0,
                    "max_value": 200.0,
                    "description": "スケール係数",
                },
            },
            "pandas_function": "pvo",
            "data_columns": ["Volume"],
            "returns": "multiple",
            "return_cols": ["PVO", "PVOs", "PVOh"],
            "multi_column": True,
            "default_values": {"fast": 12, "slow": 26, "signal": 9, "scalar": 100.0},
            "min_length_func": None,
            # パラメータ依存関係制約: fast期間 < slow期間
            "parameter_constraints": [
                {"type": "less_than", "param1": "fast", "param2": "slow"},
            ],
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand}_0 > 0",
                "short": "{left_operand}_0 < 0",
            },
            "scale_type": "momentum_zero_centered",
            "thresholds": {"zero_cross": True},
            "type": "volume",
        },
    },
    "PVT": {
        "config": {
            "result_type": "single",
            "scale_type": "momentum_zero_centered",
            "category": "volume",
            "adapter_function": "app.services.indicators.technical_indicators.volume.VolumeIndicators.pvt",
            "required_data": ["close", "volume"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {},
            "parameters": {},
            "pandas_function": "pvt",
            "data_column": None,
            "data_columns": ["Close", "Volume"],
            "returns": "single",
            "return_cols": None,
            "multi_column": True,
            "default_values": {},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand} > {threshold}",
                "short": "{left_operand} < {threshold}",
            },
            "scale_type": "momentum_zero_centered",
            "thresholds": {"normal": {"threshold": 0}},
            "type": "volume",
        },
    },
    "NVI": {
        "config": {
            "result_type": "single",
            "scale_type": "momentum_zero_centered",
            "category": "volume",
            "adapter_function": "app.services.indicators.technical_indicators.volume.VolumeIndicators.nvi",
            "required_data": ["close", "volume"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {},
            "parameters": {},
            "pandas_function": "nvi",
            "data_column": None,
            "data_columns": ["Close", "Volume"],
            "returns": "single",
            "return_cols": None,
            "multi_column": True,
            "default_values": {},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {
                "long": "{left_operand} > {threshold}",
                "short": "{left_operand} < {threshold}",
            },
            "scale_type": "momentum_zero_centered",
            "thresholds": {"normal": {"threshold": 0}},
            "type": "volume",
        },
    },
    "VWAP": {
        "config": {
            "result_type": "single",
            "scale_type": "volume",
            "category": "volume",
            "adapter_function": "app.services.indicators.technical_indicators.volume.VolumeIndicators.vwap",
            "required_data": ["high", "low", "close", "volume"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {},
            "parameters": {},
            "pandas_function": None,
            "data_column": None,
            "data_columns": None,
            "returns": "single",
            "return_cols": None,
            "multi_column": False,
            "default_values": {},
            "min_length_func": None,
            "absolute_min_length": 2,
        },
        "yaml": {
            "conditions": {
                "long": "close > {left_operand}",
                "short": "close < {left_operand}",
            },
            "scale_type": "price_absolute",
            "thresholds": None,
            "type": "volume",
        },
    },
    "VWAP_Z": {
        "config": {
            "result_type": "single",
            "scale_type": "oscillator_plus_minus_100",
            "category": "volume",
            "adapter_function": "app.services.indicators.technical_indicators.volume.VolumeIndicators.vwap_z_score",
            "required_data": ["high", "low", "close", "volume"],
            "output_names": None,
            "default_output": None,
            "aliases": ["VWAP_DIVERGENCE"],
            "param_map": {
                "period": "period",
            },
            "parameters": {
                "period": {
                    "default_value": 20,
                    "min_value": 2,
                    "max_value": 200,
                    "description": "VWAP Z-Score period",
                }
            },
            "pandas_function": None,
            "data_column": None,
            "data_columns": ["High", "Low", "Close", "Volume"],
            "returns": "single",
            "return_cols": None,
            "multi_column": True,
            "default_values": {"period": 20},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {},
            "scale_type": "oscillator_plus_minus_100",
            "thresholds": None,
            "type": "volume",
        },
    },
    "RVOL": {
        "config": {
            "result_type": "single",
            "scale_type": "price_ratio",
            "category": "volume",
            "adapter_function": "app.services.indicators.technical_indicators.volume.VolumeIndicators.rvol",
            "required_data": ["volume"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {"window": "window"},
            "parameters": {
                "window": {
                    "default_value": 20,
                    "min_value": 2,
                    "max_value": 200,
                    "description": "RVOL lookback window",
                }
            },
            "pandas_function": None,
            "data_column": None,
            "data_columns": ["Volume"],
            "returns": "single",
            "return_cols": None,
            "multi_column": True,
            "default_values": {"window": 20},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {},
            "scale_type": "price_ratio",
            "thresholds": None,
            "type": "volume",
        },
    },
    "ABSORPTION": {
        "config": {
            "result_type": "single",
            "scale_type": "price_ratio",
            "category": "volume",
            "adapter_function": "app.services.indicators.technical_indicators.volume.VolumeIndicators.absorption_score",
            "required_data": ["high", "low", "volume"],
            "output_names": None,
            "default_output": None,
            "aliases": None,
            "param_map": {
                "window": "window",
            },
            "parameters": {
                "window": {
                    "default_value": 20,
                    "min_value": 2,
                    "max_value": 200,
                    "description": "Absorption score window",
                }
            },
            "pandas_function": None,
            "data_column": None,
            "data_columns": ["High", "Low", "Volume"],
            "returns": "single",
            "return_cols": None,
            "multi_column": True,
            "default_values": {"window": 20},
            "min_length_func": None,
        },
        "yaml": {
            "conditions": {},
            "scale_type": "price_ratio",
            "thresholds": None,
            "type": "volume",
        },
    },
}



