/**
 * オートストラテジー関連の型定義
 */

/**
 * 統合戦略データ
 * ショーケース戦略とオートストラテジー戦略の統合形式
 */
export interface UnifiedStrategy {
  /** 戦略ID（プレフィックス付き: showcase_1, auto_1） */
  id: string;
  /** 戦略名 */
  name: string;
  /** 戦略の説明 */
  description: string;
  /** カテゴリ */
  category: string;
  /** 使用指標リスト */
  indicators: string[];
  /** パラメータ */
  parameters: Record<string, any>;
  /** 期待リターン */
  expected_return: number;
  /** シャープレシオ */
  sharpe_ratio: number;
  /** 最大ドローダウン */
  max_drawdown: number;
  /** 勝率 */
  win_rate: number;
  /** リスクレベル */
  risk_level: "low" | "medium" | "high";
  /** 推奨時間軸 */
  recommended_timeframe: string;
  /** データソース */
  source: "showcase" | "auto_strategy";
  /** 実験ID（オートストラテジーの場合） */
  experiment_id?: number;
  /** 世代数（オートストラテジーの場合） */
  generation?: number;
  /** フィットネススコア（オートストラテジーの場合） */
  fitness_score?: number;
  /** 作成日時 */
  created_at: string;
  /** 更新日時 */
  updated_at: string;
}

/**
 * 統合戦略レスポンス
 */
export interface UnifiedStrategiesResponse {
  success: boolean;
  strategies: UnifiedStrategy[];
  total_count: number;
  has_more: boolean;
  message: string;
  timestamp: string;
}

/**
 * オートストラテジー戦略データ
 */
export interface AutoGeneratedStrategy extends UnifiedStrategy {
  source: "auto_strategy";
  experiment_id: number;
  generation: number;
  fitness_score: number;
  /** 遺伝子データ */
  gene_data?: {
    indicators: Record<string, any>;
    entry_conditions: Record<string, any>;
    exit_conditions: Record<string, any>;
    risk_management: Record<string, any>;
  };
}

/**
 * 戦略統計情報
 */
export interface StrategyStatistics {
  /** 総戦略数 */
  total_strategies: number;
  /** ショーケース戦略数 */
  showcase_strategies: number;
  /** オートストラテジー戦略数 */
  auto_generated_strategies: number;
  /** カテゴリ別分布 */
  categories: Record<string, number>;
  /** リスクレベル別分布 */
  risk_levels: Record<string, number>;
  /** パフォーマンス統計 */
  performance_summary: {
    avg_return: number;
    avg_sharpe_ratio: number;
    avg_max_drawdown: number;
    avg_win_rate: number;
  };
}

/**
 * 戦略統計レスポンス
 */
export interface StrategyStatsResponse {
  success: boolean;
  stats: StrategyStatistics;
  message: string;
  timestamp: string;
}

/**
 * 戦略フィルター（拡張版）
 */
export interface UnifiedStrategyFilter {
  /** カテゴリフィルター */
  category?: string;
  /** リスクレベルフィルター */
  risk_level?: "low" | "medium" | "high";
  /** データソースフィルター */
  source?: "showcase" | "auto_strategy" | "all";
  /** 最小リターン */
  min_return?: number;
  /** 最大リターン */
  max_return?: number;
  /** 最小シャープレシオ */
  min_sharpe?: number;
  /** 最大シャープレシオ */
  max_sharpe?: number;
  /** 最小ドローダウン */
  min_drawdown?: number;
  /** 最大ドローダウン */
  max_drawdown?: number;
  /** 検索クエリ */
  search_query?: string;
  /** 実験IDフィルター（オートストラテジーの場合） */
  experiment_id?: number;
  /** 最小フィットネススコア（オートストラテジーの場合） */
  min_fitness?: number;
}

/**
 * ページネーション（拡張版）
 */
export interface UnifiedPagination {
  /** 取得件数制限 */
  limit: number;
  /** オフセット */
  offset: number;
  /** ソート項目 */
  sort_by: "created_at" | "expected_return" | "sharpe_ratio" | "max_drawdown" | "win_rate" | "fitness_score";
  /** ソート順序 */
  sort_order: "asc" | "desc";
}

/**
 * カテゴリ情報
 */
export interface CategoryInfo {
  value: string;
  label: string;
}

/**
 * リスクレベル情報
 */
export interface RiskLevelInfo {
  value: "low" | "medium" | "high";
  label: string;
  description: string;
}

/**
 * カテゴリレスポンス
 */
export interface CategoriesResponse {
  success: boolean;
  categories: CategoryInfo[];
  message: string;
}

/**
 * リスクレベルレスポンス
 */
export interface RiskLevelsResponse {
  success: boolean;
  risk_levels: RiskLevelInfo[];
  message: string;
}

/**
 * GA実験情報
 */
export interface GAExperiment {
  id: number;
  name: string;
  status: "running" | "completed" | "failed";
  progress: number;
  best_fitness?: number;
  total_generations?: number;
  current_generation: number;
  created_at: string;
  completed_at?: string;
}

/**
 * 戦略詳細情報（モーダル表示用）
 */
export interface StrategyDetail extends UnifiedStrategy {
  /** バックテスト結果詳細 */
  backtest_details?: {
    total_trades: number;
    winning_trades: number;
    losing_trades: number;
    profit_factor: number;
    avg_win: number;
    avg_loss: number;
    equity_curve?: Array<{
      timestamp: string;
      equity: number;
    }>;
    trade_history?: Array<{
      entry_time: string;
      exit_time: string;
      entry_price: number;
      exit_price: number;
      pnl: number;
      return_pct: number;
    }>;
  };
  /** GA実験情報（オートストラテジーの場合） */
  experiment_info?: GAExperiment;
}

/**
 * API エラーレスポンス
 */
export interface APIError {
  success: false;
  error: string;
  detail?: string;
  timestamp: string;
}

/**
 * 戦略パフォーマンス指標
 */
export interface PerformanceMetrics {
  total_return: number;
  sharpe_ratio: number;
  max_drawdown: number;
  win_rate: number;
  profit_factor: number;
  total_trades: number;
  winning_trades: number;
  losing_trades: number;
  avg_win: number;
  avg_loss: number;
}

/**
 * 戦略比較データ
 */
export interface StrategyComparison {
  strategies: UnifiedStrategy[];
  comparison_metrics: {
    best_return: UnifiedStrategy;
    best_sharpe: UnifiedStrategy;
    lowest_drawdown: UnifiedStrategy;
    highest_win_rate: UnifiedStrategy;
  };
  correlation_matrix?: number[][];
}
