/**
 * オートストラテジー関連の型定義
 */

/**
 * 統合戦略データ
 * ショーケース戦略とオートストラテジー戦略の統合形式
 */
export interface UnifiedStrategy {
  /** 戦略ID（プレフィックス付き: auto_1） */
  id: string;
  /** 戦略名 */
  name: string;
  /** 戦略の説明 */
  description: string;
  /** カテゴリ */
  category: string;
  /** 使用指標リスト（例: "RSI", "MACD", "BBANDS" など） */
  indicators: string[];
  /** パラメータ（キー=指標/ルール名、値=設定値。例: {"RSI.period":14}） */
  parameters: Record<string, any>;
  /** 期待リターン（期間に依存。UI側で%表示に変換推奨） */
  expected_return: number;
  /** シャープレシオ */
  sharpe_ratio: number;
  /** 最大ドローダウン（0-1の割合または%換算前の値想定） */
  max_drawdown: number;
  /** 勝率（0-1の割合。UIで%表示推奨） */
  win_rate: number;
  /** リスクレベル */
  risk_level: "low" | "medium" | "high";
  /** 推奨時間軸（例: "1h", "4h", "1d"） */
  recommended_timeframe: string;
  /** データソース */
  source: "auto_strategy";
  /** 実験ID（オートストラテジーの場合） */
  experiment_id?: number;
  /** 世代数（オートストラテジーの場合） */
  generation?: number;
  /** フィットネススコア（オートストラテジーの場合） */
  fitness_score?: number;
  /** フィットネス値（多目的最適化の場合。目的関数の並びに依存） */
  fitness_values?: number[];
  /** 作成日時（ISO文字列） */
  created_at: string;
  /** 更新日時（ISO文字列） */
  updated_at: string;
}

/**
 * 統合戦略レスポンス
 */
export interface UnifiedStrategiesResponse {
  /** 成功フラグ */
  success: boolean;
  /** 戦略一覧 */
  strategies: UnifiedStrategy[];
  /** 総件数（ページネーション用） */
  total_count: number;
  /** 次ページが存在するか */
  has_more: boolean;
  /** サーバーメッセージ（警告/補足など） */
  message: string;
  /** レスポンス生成時刻（ISO文字列） */
  timestamp: string;
}

/**
 * オートストラテジー戦略データ
 */
export interface AutoGeneratedStrategy extends UnifiedStrategy {
  source: "auto_strategy";
  experiment_id: number;
  generation: number;
  fitness_score: number;
  /** 遺伝子データ（GA内部表現。例: 指標と閾値/窓長、条件式の構文木など） */
  gene_data?: {
    /** 指標定義（例: {"RSI":{"period":14}}） */
    indicators: Record<string, any>;
    /** エントリー条件（内部DSL/AST想定） */
    entry_conditions: Record<string, any>;
    /** エグジット条件（内部DSL/AST想定） */
    exit_conditions: Record<string, any>;
    /** リスク管理（ポジションサイズ/TP/SLなど） */
    risk_management: Record<string, any>;
  };
}

/**
 * 戦略統計情報
 */
export interface StrategyStatistics {
  /** 総戦略数 */
  total_strategies: number;
  /** オートストラテジー戦略数 */
  auto_generated_strategies: number;
  /** カテゴリ別分布（キー=カテゴリ名、値=件数） */
  categories: Record<string, number>;
  /** リスクレベル別分布（キー=low/medium/high、値=件数） */
  risk_levels: Record<string, number>;
  /** パフォーマンス統計（平均値） */
  performance_summary: {
    /** 平均リターン */
    avg_return: number;
    /** 平均シャープレシオ */
    avg_sharpe_ratio: number;
    /** 平均最大DD */
    avg_max_drawdown: number;
    /** 平均勝率 */
    avg_win_rate: number;
  };
}

/**
 * 戦略統計レスポンス
 */
export interface StrategyStatsResponse {
  /** 成功フラグ */
  success: boolean;
  /** 統計情報 */
  stats: StrategyStatistics;
  /** サーバーメッセージ */
  message: string;
  /** レスポンス生成時刻（ISO文字列） */
  timestamp: string;
}

/**
 * 戦略フィルター（拡張版）
 */
export interface UnifiedStrategyFilter {
  /** カテゴリフィルター */
  category?: string;
  /** リスクレベルフィルター */
  risk_level?: "low" | "medium" | "high";
  /** データソースフィルター */
  source?: "auto_strategy" | "all";
  /** 最小リターン */
  min_return?: number;
  /** 最大リターン */
  max_return?: number;
  /** 最小シャープレシオ */
  min_sharpe?: number;
  /** 最大シャープレシオ */
  max_sharpe?: number;
  /** 最小ドローダウン */
  min_drawdown?: number;
  /** 最大ドローダウン */
  max_drawdown?: number;
  /** 検索クエリ（name/description/indicators を対象とする想定） */
  search_query?: string;
  /** 実験IDフィルター（オートストラテジーの場合） */
  experiment_id?: number;
  /** 最小フィットネススコア（オートストラテジーの場合） */
  min_fitness?: number;
}

/**
 * ページネーション（拡張版）
 */
export interface UnifiedPagination {
  /** 取得件数制限（ページサイズ） */
  limit: number;
  /** オフセット（先頭からのスキップ件数） */
  offset: number;
  /** ソート項目（指標により昇順/降順の見栄えが異なる点に注意） */
  sort_by:
    | "created_at"
    | "expected_return"
    | "sharpe_ratio"
    | "max_drawdown"
    | "win_rate"
    | "fitness_score";
  /** ソート順序 */
  sort_order: "asc" | "desc";
}

/**
 * カテゴリ情報
 */
export interface CategoryInfo {
  /** フィルタ用の値 */
  value: string;
  /** 表示用ラベル */
  label: string;
}

/**
 * リスクレベル情報
 */
export interface RiskLevelInfo {
  /** 値（内部的な列挙） */
  value: "low" | "medium" | "high";
  /** 表示用ラベル */
  label: string;
  /** 説明文（ユーザー向け補足） */
  description: string;
}

/**
 * カテゴリレスポンス
 */
export interface CategoriesResponse {
  /** 成功フラグ */
  success: boolean;
  /** カテゴリ一覧 */
  categories: CategoryInfo[];
  /** サーバーメッセージ */
  message: string;
}

/**
 * リスクレベルレスポンス
 */
export interface RiskLevelsResponse {
  /** 成功フラグ */
  success: boolean;
  /** リスクレベル一覧 */
  risk_levels: RiskLevelInfo[];
  /** サーバーメッセージ */
  message: string;
}

/**
 * GA実験情報
 */
export interface GAExperiment {
  /** 実験ID */
  id: number;
  /** 実験名 */
  name: string;
  /** ステータス */
  status: "running" | "completed" | "failed";
  /** 進捗（0-1） */
  progress: number;
  /** これまでの最良フィットネス */
  best_fitness?: number;
  /** 総世代数（確定後に設定される場合あり） */
  total_generations?: number;
  /** 現在の世代 */
  current_generation: number;
  /** 作成日時（ISO文字列） */
  created_at: string;
  /** 完了日時（完了時のみ、ISO文字列） */
  completed_at?: string;
}

/**
 * 戦略詳細情報（モーダル表示用）
 */
export interface StrategyDetail extends UnifiedStrategy {
  /** バックテスト結果詳細 */
  backtest_details?: {
    /** 総取引数 */
    total_trades: number;
    /** 勝ちトレード数 */
    winning_trades: number;
    /** 負けトレード数 */
    losing_trades: number;
    /** プロフィットファクター（総利益/総損失） */
    profit_factor: number;
    /** 平均勝ち額 */
    avg_win: number;
    /** 平均負け額 */
    avg_loss: number;
    /** 資産曲線（時系列。timestampはISO文字列） */
    equity_curve?: Array<{
      timestamp: string;
      equity: number;
    }>;
    /** 取引履歴（エントリー/エグジットの価格・時刻・損益） */
    trade_history?: Array<{
      entry_time: string;
      exit_time: string;
      entry_price: number;
      exit_price: number;
      pnl: number;
      return_pct: number;
    }>;
  };
  /** GA実験情報（オートストラテジーの場合） */
  experiment_info?: GAExperiment;
}
