"""Add LongShortRatioData table

Revision ID: 515fd9c63048
Revises: 83814013178d
Create Date: 2025-12-10 17:48:06.555901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '515fd9c63048'
down_revision: Union[str, None] = '83814013178d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('long_short_ratio_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('buy_ratio', sa.Float(), nullable=False),
    sa.Column('sell_ratio', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ls_symbol_period_timestamp', 'long_short_ratio_data', ['symbol', 'period', 'timestamp'], unique=False)
    op.create_index('idx_ls_timestamp_symbol', 'long_short_ratio_data', ['timestamp', 'symbol'], unique=False)
    op.create_index(op.f('ix_long_short_ratio_data_period'), 'long_short_ratio_data', ['period'], unique=False)
    op.create_index(op.f('ix_long_short_ratio_data_symbol'), 'long_short_ratio_data', ['symbol'], unique=False)
    op.create_index(op.f('ix_long_short_ratio_data_timestamp'), 'long_short_ratio_data', ['timestamp'], unique=False)
    op.create_index('uq_symbol_period_timestamp', 'long_short_ratio_data', ['symbol', 'period', 'timestamp'], unique=True)
    # op.drop_column('ga_experiments', 'best_fitness_values')
    # op.drop_column('ga_experiments', 'hypervolume')
    # op.drop_column('generated_strategies', 'hypervolume')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('generated_strategies', sa.Column('hypervolume', sa.FLOAT(), nullable=True))
    # op.add_column('ga_experiments', sa.Column('hypervolume', sa.FLOAT(), nullable=True))
    # op.add_column('ga_experiments', sa.Column('best_fitness_values', sqlite.JSON(), nullable=True))
    op.drop_index('uq_symbol_period_timestamp', table_name='long_short_ratio_data')
    op.drop_index(op.f('ix_long_short_ratio_data_timestamp'), table_name='long_short_ratio_data')
    op.drop_index(op.f('ix_long_short_ratio_data_symbol'), table_name='long_short_ratio_data')
    op.drop_index(op.f('ix_long_short_ratio_data_period'), table_name='long_short_ratio_data')
    op.drop_index('idx_ls_timestamp_symbol', table_name='long_short_ratio_data')
    op.drop_index('idx_ls_symbol_period_timestamp', table_name='long_short_ratio_data')
    op.drop_table('long_short_ratio_data')
    # ### end Alembic commands ###
