"""Create initial tables

Revision ID: 83814013178d
Revises:
Create Date: 2025-08-27 04:09:11.283576

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "83814013178d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "backtest_results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("strategy_name", sa.String(length=100), nullable=False),
        sa.Column("symbol", sa.String(length=50), nullable=False),
        sa.Column("timeframe", sa.String(length=10), nullable=False),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("initial_capital", sa.Float(), nullable=False),
        sa.Column("commission_rate", sa.Float(), nullable=True),
        sa.Column("config_json", sa.JSON(), nullable=False),
        sa.Column("performance_metrics", sa.JSON(), nullable=False),
        sa.Column("equity_curve", sa.JSON(), nullable=False),
        sa.Column("trade_history", sa.JSON(), nullable=False),
        sa.Column("execution_time", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_backtest_created_at", "backtest_results", ["created_at"], unique=False
    )
    op.create_index(
        "idx_backtest_strategy_created",
        "backtest_results",
        ["strategy_name", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_backtest_symbol_timeframe",
        "backtest_results",
        ["symbol", "timeframe"],
        unique=False,
    )
    op.create_index(
        op.f("ix_backtest_results_symbol"), "backtest_results", ["symbol"], unique=False
    )
    op.create_index(
        op.f("ix_backtest_results_timeframe"),
        "backtest_results",
        ["timeframe"],
        unique=False,
    )
    op.create_table(
        "funding_rate_data",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=50), nullable=False),
        sa.Column("funding_rate", sa.Float(), nullable=False),
        sa.Column("funding_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("next_funding_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("mark_price", sa.Float(), nullable=True),
        sa.Column("index_price", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_funding_symbol_created",
        "funding_rate_data",
        ["symbol", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_funding_symbol_timestamp",
        "funding_rate_data",
        ["symbol", "funding_timestamp"],
        unique=False,
    )
    op.create_index(
        "idx_funding_timestamp_symbol",
        "funding_rate_data",
        ["funding_timestamp", "symbol"],
        unique=False,
    )
    op.create_index(
        op.f("ix_funding_rate_data_funding_timestamp"),
        "funding_rate_data",
        ["funding_timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_funding_rate_data_symbol"),
        "funding_rate_data",
        ["symbol"],
        unique=False,
    )
    op.create_index(
        op.f("ix_funding_rate_data_timestamp"),
        "funding_rate_data",
        ["timestamp"],
        unique=False,
    )
    op.create_index(
        "uq_symbol_funding_timestamp",
        "funding_rate_data",
        ["symbol", "funding_timestamp"],
        unique=True,
    )
    op.create_table(
        "ga_experiments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("best_fitness", sa.Float(), nullable=True),
        sa.Column("total_generations", sa.Integer(), nullable=True),
        sa.Column("current_generation", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_ga_experiments_created", "ga_experiments", ["created_at"], unique=False
    )
    op.create_index(
        "idx_ga_experiments_status", "ga_experiments", ["status"], unique=False
    )
    op.create_table(
        "ohlcv_data",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=50), nullable=False),
        sa.Column("timeframe", sa.String(length=10), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("open", sa.Float(), nullable=False),
        sa.Column("high", sa.Float(), nullable=False),
        sa.Column("low", sa.Float(), nullable=False),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("volume", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_symbol_timeframe_timestamp",
        "ohlcv_data",
        ["symbol", "timeframe", "timestamp"],
        unique=False,
    )
    op.create_index(
        "idx_timestamp_symbol", "ohlcv_data", ["timestamp", "symbol"], unique=False
    )
    op.create_index(
        op.f("ix_ohlcv_data_symbol"), "ohlcv_data", ["symbol"], unique=False
    )
    op.create_index(
        op.f("ix_ohlcv_data_timeframe"), "ohlcv_data", ["timeframe"], unique=False
    )
    op.create_index(
        op.f("ix_ohlcv_data_timestamp"), "ohlcv_data", ["timestamp"], unique=False
    )
    op.create_index(
        "uq_symbol_timeframe_timestamp",
        "ohlcv_data",
        ["symbol", "timeframe", "timestamp"],
        unique=True,
    )
    op.create_table(
        "open_interest_data",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=50), nullable=False),
        sa.Column("open_interest_value", sa.Float(), nullable=False),
        sa.Column("data_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_oi_data_timestamp_symbol",
        "open_interest_data",
        ["data_timestamp", "symbol"],
        unique=False,
    )
    op.create_index(
        "idx_oi_symbol_created",
        "open_interest_data",
        ["symbol", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_oi_symbol_data_timestamp",
        "open_interest_data",
        ["symbol", "data_timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_open_interest_data_data_timestamp"),
        "open_interest_data",
        ["data_timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_open_interest_data_symbol"),
        "open_interest_data",
        ["symbol"],
        unique=False,
    )
    op.create_index(
        op.f("ix_open_interest_data_timestamp"),
        "open_interest_data",
        ["timestamp"],
        unique=False,
    )
    op.create_index(
        "uq_symbol_data_timestamp",
        "open_interest_data",
        ["symbol", "data_timestamp"],
        unique=True,
    )
    op.create_table(
        "generated_strategies",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("experiment_id", sa.Integer(), nullable=False),
        sa.Column("gene_data", sa.JSON(), nullable=False),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("fitness_score", sa.Float(), nullable=True),
        sa.Column("fitness_values", sa.JSON(), nullable=True),
        sa.Column("parent_ids", sa.JSON(), nullable=True),
        sa.Column("backtest_result_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["backtest_result_id"],
            ["backtest_results.id"],
        ),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["ga_experiments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_generated_strategies_experiment",
        "generated_strategies",
        ["experiment_id"],
        unique=False,
    )
    op.create_index(
        "idx_generated_strategies_fitness",
        "generated_strategies",
        ["fitness_score"],
        unique=False,
    )
    op.create_index(
        "idx_generated_strategies_generation",
        "generated_strategies",
        ["generation"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_generated_strategies_generation", table_name="generated_strategies"
    )
    op.drop_index("idx_generated_strategies_fitness", table_name="generated_strategies")
    op.drop_index(
        "idx_generated_strategies_experiment", table_name="generated_strategies"
    )
    op.drop_table("generated_strategies")
    op.drop_index("uq_symbol_data_timestamp", table_name="open_interest_data")
    op.drop_index(
        op.f("ix_open_interest_data_timestamp"), table_name="open_interest_data"
    )
    op.drop_index(op.f("ix_open_interest_data_symbol"), table_name="open_interest_data")
    op.drop_index(
        op.f("ix_open_interest_data_data_timestamp"), table_name="open_interest_data"
    )
    op.drop_index("idx_oi_symbol_data_timestamp", table_name="open_interest_data")
    op.drop_index("idx_oi_symbol_created", table_name="open_interest_data")
    op.drop_index("idx_oi_data_timestamp_symbol", table_name="open_interest_data")
    op.drop_table("open_interest_data")
    op.drop_index("uq_symbol_timeframe_timestamp", table_name="ohlcv_data")
    op.drop_index(op.f("ix_ohlcv_data_timestamp"), table_name="ohlcv_data")
    op.drop_index(op.f("ix_ohlcv_data_timeframe"), table_name="ohlcv_data")
    op.drop_index(op.f("ix_ohlcv_data_symbol"), table_name="ohlcv_data")
    op.drop_index("idx_timestamp_symbol", table_name="ohlcv_data")
    op.drop_index("idx_symbol_timeframe_timestamp", table_name="ohlcv_data")
    op.drop_table("ohlcv_data")
    op.drop_index("idx_ga_experiments_status", table_name="ga_experiments")
    op.drop_index("idx_ga_experiments_created", table_name="ga_experiments")
    op.drop_table("ga_experiments")
    op.drop_index("uq_symbol_funding_timestamp", table_name="funding_rate_data")
    op.drop_index(
        op.f("ix_funding_rate_data_timestamp"), table_name="funding_rate_data"
    )
    op.drop_index(op.f("ix_funding_rate_data_symbol"), table_name="funding_rate_data")
    op.drop_index(
        op.f("ix_funding_rate_data_funding_timestamp"), table_name="funding_rate_data"
    )
    op.drop_index("idx_funding_timestamp_symbol", table_name="funding_rate_data")
    op.drop_index("idx_funding_symbol_timestamp", table_name="funding_rate_data")
    op.drop_index("idx_funding_symbol_created", table_name="funding_rate_data")
    op.drop_table("funding_rate_data")
    op.drop_index(op.f("ix_backtest_results_timeframe"), table_name="backtest_results")
    op.drop_index(op.f("ix_backtest_results_symbol"), table_name="backtest_results")
    op.drop_index("idx_backtest_symbol_timeframe", table_name="backtest_results")
    op.drop_index("idx_backtest_strategy_created", table_name="backtest_results")
    op.drop_index("idx_backtest_created_at", table_name="backtest_results")
    op.drop_table("backtest_results")
    # ### end Alembic commands ###
