"""Add fitness_values to GeneratedStrategy

Revision ID: b845baffd21c
Revises:
Create Date: 2025-07-16 19:03:11.650643

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b845baffd21c"
down_revision: Union[str, None] = "697605ce99b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "generated_strategies", sa.Column("fitness_values", sa.JSON(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("generated_strategies", "fitness_values")
    # ### end Alembic commands ###
