indicators:
  ACCBANDS:
    conditions:
      long: close > {left_operand}_lower
      short: close < {left_operand}_upper
    scale_type: price_absolute
    thresholds:
      aggressive:
        acceleration: 0.005
      conservative:
        acceleration: 0.02
      normal:
        acceleration: 0.01
    type: volatility
  AD:
    conditions:
      long: close > {left_operand}
      short: close < {left_operand}
    scale_type: price_absolute
    thresholds: null
    type: volume
  ADOSC:
    conditions:
      long: '{left_operand} > {threshold}'
      short: '{left_operand} < {threshold}'
    scale_type: momentum_zero_centered
    thresholds:
      aggressive:
        long_gt: -10000
        short_lt: 10000
      conservative:
        long_gt: -2000
        short_lt: 2000
      normal:
        long_gt: -5000
        short_lt: 5000
    type: volume
  EFI:
    conditions:
      long: '{left_operand} > {threshold}'
      short: '{left_operand} < {threshold}'
    scale_type: momentum_zero_centered
    thresholds:
      all:
        long_gt: 0
        short_lt: 0
    type: volume
  ADX:
    conditions:
      long: '{left_operand} > {threshold}'
      short: '{left_operand} > {threshold}'
    scale_type: oscillator_0_100
    thresholds:
      aggressive:
        trend_min: 18
      conservative:
        trend_min: 30
      normal:
        trend_min: 25
    type: momentum
  ATR:
    conditions:
      long: close > {left_operand}_current + {multiplier}
      short: close < {left_operand}_current - {multiplier}
    scale_type: price_absolute
    thresholds:
      aggressive:
        multiplier: 0.5
      conservative:
        multiplier: 1.5
      normal:
        multiplier: 1.0
    type: volatility
  BBANDS:
    components:
    - upper
    - middle
    - lower
    conditions:
      long: close < {left_operand}_lower
      short: close > {left_operand}_upper
    scale_type: price_absolute
    thresholds: null
    type: volatility
  BB:
    components:
    - upper
    - middle
    - lower
    conditions:
      long: close < {left_operand}_lower
      short: close > {left_operand}_upper
    scale_type: price_absolute
    thresholds: null
    type: volatility
  CCI:
    conditions:
      long: '{left_operand} > {long_threshold}'
      short: '{left_operand} < {short_threshold}'
    scale_type: oscillator_plus_minus_100
    thresholds:
      aggressive:
        abs_limit: 100
        long_lt: -100
      conservative:
        abs_limit: 100
        long_lt: -100
      normal:
        abs_limit: 100
        long_lt: -100
    type: momentum
  CMF:
    conditions:
      long: close > {left_operand}_mid
      short: close < {left_operand}_mid
    scale_type: price_absolute
    thresholds:
      aggressive:
        multiplier: 1.5
      conservative:
        multiplier: 2.5
      normal:
        multiplier: 2.0
    type: volume
  DONCHIAN:
    conditions:
      long: close > {left_operand}_mid
      short: close < {left_operand}_mid
    scale_type: price_absolute
    thresholds:
      aggressive:
        period: 10
      combo:
        condition: (close - lower) / (upper - lower) >= primary or (close - lower)
          / (upper - lower) <= secondary
        primary: 0.9
        secondary: 0.1
      conservative:
        period: 30
      normal:
        period: 20
      range:
        break_out_threshold: 0.8
        consolidation_threshold: 0.3
    type: volatility
  DEMA:
    conditions:
      long: close > {left_operand}
      short: close < {left_operand}
    scale_type: price_absolute
    thresholds: null
    type: trend
  EMA:
    conditions:
      long: close > {left_operand}
      short: close < {left_operand}
    scale_type: price_absolute
    thresholds: "close"
    type: trend
  KAMA:
    conditions:
      long: close > {left_operand}
      short: close < {left_operand}
    scale_type: price_absolute
    thresholds:
      aggressive:
        efficiency_ratio: 2.5
      conservative:
        efficiency_ratio: 10.0
      normal:
        efficiency_ratio: 5.0
    type: price_transform
  KELTNER:
    conditions:
      long: close > {left_operand}_upper
      short: close < {left_operand}_lower
    scale_type: price_absolute
    thresholds:
      aggressive:
        multiplier: 1.0
      combo:
        condition: distance >= primary or distance <= secondary
        primary: 2.5
        secondary: -2.5
      conservative:
        multiplier: 2.0
      normal:
        multiplier: 1.5
      range:
        break_out_lower: -1.8
        break_out_upper: 1.8
    type: volatility
  MACD:
    conditions:
      long: '{left_operand}_0 > 0'
      short: '{left_operand}_0 < 0'
    scale_type: momentum_zero_centered
    thresholds:
      zero_cross: true
    type: momentum
  MFI:
    conditions:
      long: '{left_operand} < {threshold}'
      short: '{left_operand} > {threshold}'
    scale_type: oscillator_0_100
    thresholds:
      aggressive:
        long_lt: 20
        short_gt: 85
      conservative:
        long_lt: 40
        short_gt: 60
      normal:
        long_lt: 30
        short_gt: 70
    type: volume
  MOM:
    conditions:
      long: '{left_operand} > {threshold}'
      short: '{left_operand} < {threshold}'
    scale_type: momentum_zero_centered
    thresholds:
      aggressive:
        long_lt: -10
        short_gt: 10
      conservative:
        long_lt: -2
        short_gt: 2
      normal:
        long_lt: -5
        short_gt: 5
    type: momentum
  OBV:
    conditions:
      long: '{left_operand} > 0'
      short: '{left_operand} < 0'
    scale_type: momentum_zero_centered
    thresholds:
      zero_cross: true
    type: volume
  QQE:
    conditions:
      long: '{left_operand} < {threshold}'
      short: '{left_operand} > {threshold}'
    scale_type: oscillator_0_100
    thresholds:
      aggressive:
        long_lt: 15
        short_gt: 85
      conservative:
        long_lt: 25
        short_gt: 75
      normal:
        long_lt: 20
        short_gt: 80
    type: momentum
  ROC:
    conditions:
      long: '{left_operand} < {threshold}'
      short: '{left_operand} > {threshold}'
    scale_type: momentum_zero_centered
    thresholds:
      aggressive:
        long_lt: -3.0
        short_gt: 3.0
      combo:
        condition: abs_value >= primary or abs_value <= -secondary
        primary: -5.0
        secondary: 5.0
      conservative:
        long_lt: -0.5
        short_gt: 0.5
      normal:
        long_lt: -1.5
        short_gt: 1.5
      range:
        long_gt: -2.0
        long_lt: 0.0
        short_gt: 0.0
        short_lt: 2.0
    type: momentum
  RSI:
    conditions:
      long: '{left_operand} > {threshold}'
      short: '{left_operand} < {threshold}'
    scale_type: oscillator_0_100
    thresholds:
      aggressive:
        long_gt: 70
        short_lt: 30
      conservative:
        long_gt: 80
        short_lt: 20
      normal:
        long_gt: 75
        short_lt: 25
    type: momentum
  SAR:
    conditions:
      long: close > {left_operand}
      short: close < {left_operand}
    scale_type: price_absolute
    thresholds: null
    type: trend
  SQUEEZE:
    conditions:
      long: '{left_operand} < {threshold}'
      short: '{left_operand} > {threshold}'
    scale_type: oscillator_0_100
    thresholds:
      aggressive:
        long_lt: 15
        short_gt: 85
      normal:
        long_lt: 20
        short_gt: 80
      conservative:
        long_lt: 25
        short_gt: 75
    type: momentum
  SMA:
    conditions:
      long: close > {left_operand}
      short: close < {left_operand}
    scale_type: price_absolute
    thresholds: null
    type: trend
  STOCH:
    conditions:
      long: '{left_operand}_0 < {threshold}'
      short: '{left_operand}_0 > {threshold}'
    scale_type: oscillator_0_100
    thresholds:
      aggressive:
        long_lt: 15
        short_gt: 85
      conservative:
        long_lt: 25
        short_gt: 75
      normal:
        long_lt: 20
        short_gt: 80
    type: momentum
  SUPERTREND:
    components:
    - lower
    - upper
    - direction
    conditions:
      long: '{left_operand}_2 > 0'
      short: '{left_operand}_2 < 0'
    scale_type: price_absolute
    thresholds:
      aggressive:
        multiplier: 1.5
      conservative:
        multiplier: 4.5
      normal:
        multiplier: 3.0
    type: volatility
  T3:
    conditions:
      long: close > {left_operand}
      short: close < {left_operand}
    scale_type: price_absolute
    thresholds: null
    type: trend
  TEMA:
    conditions:
      long: close > {left_operand}
      short: close < {left_operand}
    scale_type: price_absolute
    thresholds: null
    type: trend
  UI:
    conditions:
      long: '{left_operand} < {threshold}'
      short: '{left_operand} > {threshold}'
    scale_type: oscillator_0_100
    thresholds:
      all:
        long_lt: 30
        short_gt: 70
    type: volatility
  VWAP:
    conditions:
      long: close > {left_operand}
      short: close < {left_operand}
    scale_type: price_absolute
    thresholds: null
    type: volume
  WILLR:
    conditions:
      long: '{left_operand} > {threshold}'
      short: '{left_operand} < {threshold}'
    scale_type: oscillator_plus_minus_100
    thresholds:
      aggressive:
        long_lt: -95
        short_gt: -5
      conservative:
        long_lt: -75
        short_gt: -25
      normal:
        long_lt: -80
        short_gt: -20
    type: momentum
  WMA:
    conditions:
      long: close > {left_operand}
      short: close < {left_operand}
    scale_type: price_absolute
    thresholds: null
    type: trend

# scale_types定義
scale_types:
  oscillator_0_100:
    range: [0, 100]
  oscillator_plus_minus_100:
    range: [-100, 100]
  momentum_zero_centered:
    range: null
  price_absolute:
    range: null

# デフォルト閾値マッピング
default_thresholds:
  oscillator_0_100:
    aggressive:
      long_lt: 48
    conservative:
      long_lt: 52
    normal:
      long_lt: 50
  oscillator_plus_minus_100:
    aggressive:
      long_gt: -2
    conservative:
      long_gt: 2
    normal:
      long_gt: 0
  momentum_zero_centered:
    aggressive:
      long_gt: -0.1
    conservative:
      long_gt: 0.1
    normal:
      long_gt: 0.0