indicators:
  # モメンタム系指標
  RSI:
    type: momentum
    scale_type: oscillator_0_100
    thresholds:
      aggressive:
        long_lt: 25
        short_gt: 85
      normal:
        long_lt: 30
        short_gt: 70
      conservative:
        long_lt: 35
        short_gt: 65
    conditions:
      long: "{left_operand} < {threshold}"
      short: "{left_operand} > {threshold}"

  STOCH:
    type: momentum
    scale_type: oscillator_0_100
    thresholds:
      aggressive:
        long_lt: 15
        short_gt: 85
      normal:
        long_lt: 20
        short_gt: 80
      conservative:
        long_lt: 25
        short_gt: 75
    conditions:
      long: "{left_operand}_0 < {threshold}"
      short: "{left_operand}_0 > {threshold}"

  STOCHRSI:
    type: momentum
    scale_type: oscillator_0_100
    thresholds:
      aggressive:
        long_lt: 15
        short_gt: 85
      normal:
        long_lt: 20
        short_gt: 80
      conservative:
        long_lt: 25
        short_gt: 75
    conditions:
      long: "{left_operand}_0 < {threshold}"
      short: "{left_operand}_1 < {threshold}"

  KDJ:
    type: momentum
    scale_type: oscillator_0_100
    thresholds:
      aggressive:
        long_lt: 15
        short_gt: 85
      normal:
        long_lt: 20
        short_gt: 80
      conservative:
        long_lt: 25
        short_gt: 75
    conditions:
      long: "{left_operand}_2 < {threshold}"
      short: "{left_operand}_2 > {threshold}"

  QQE:
    type: momentum
    scale_type: oscillator_0_100
    thresholds:
      aggressive:
        long_lt: 15
        short_gt: 85
      normal:
        long_lt: 20
        short_gt: 80
      conservative:
        long_lt: 25
        short_gt: 75
    conditions:
      long: "{left_operand} < {threshold}"
      short: "{left_operand} > {threshold}"

  MFI:
    type: momentum
    scale_type: oscillator_0_100
    thresholds:
      aggressive:
        long_lt: 20
        short_gt: 85
      normal:
        long_lt: 30
        short_gt: 70
      conservative:
        long_lt: 40
        short_gt: 60
    conditions:
      long: "{left_operand} < {threshold}"
      short: "{left_operand} < {threshold}"

  ADX:
    type: momentum
    scale_type: oscillator_0_100
    thresholds:
      aggressive:
        trend_min: 18
      normal:
        trend_min: 25
      conservative:
        trend_min: 30
    conditions:
      long: "{left_operand} > {threshold}"
      short: "{left_operand} > {threshold}"

  CCI:
    type: momentum
    scale_type: oscillator_plus_minus_100
    thresholds:
      aggressive:
        abs_limit: 100
        long_lt: -100
      normal:
        abs_limit: 100
        long_lt: -100
      conservative:
        abs_limit: 100
        long_lt: -100
    conditions:
      long: "{left_operand} > {long_threshold}"
      short: "{left_operand} < {short_threshold}"

  WILLR:
    type: momentum
    scale_type: oscillator_plus_minus_100
    thresholds:
      aggressive:
        long_lt: -95
        short_gt: -5
      normal:
        long_lt: -80
        short_gt: -20
      conservative:
        long_lt: -75
        short_gt: -25
    conditions:
      long: "{left_operand} > {threshold}"
      short: "{left_operand} < {threshold}"

  MACD:
    type: momentum
    scale_type: momentum_zero_centered
    thresholds: { zero_cross: true }
    conditions:
      long: "{left_operand}_0 > 0"
      short: "{left_operand}_0 < 0"

  MACDEXT:
    type: momentum
    scale_type: momentum_zero_centered
    thresholds: { zero_cross: true }
    conditions:
      long: "{left_operand}_0 > 0"
      short: "{left_operand}_0 < 0"

  # トレンド系指標
  SMA:
    type: trend
    scale_type: price_absolute
    thresholds: null
    conditions:
      long: "close > {left_operand}"
      short: "close < {left_operand}"

  EMA:
    type: trend
    scale_type: price_absolute
    thresholds: null
    conditions:
      long: "close > {left_operand}"
      short: "close < {left_operand}"

  WMA:
    type: trend
    scale_type: price_absolute
    thresholds: null
    conditions:
      long: "close > {left_operand}"
      short: "close < {left_operand}"

  KAMA:
    type: trend
    scale_type: price_absolute
    thresholds: null
    conditions:
      long: "close > {left_operand}"
      short: "close < {left_operand}"

  T3:
    type: trend
    scale_type: price_absolute
    thresholds: null
    conditions:
      long: "close > {left_operand}"
      short: "close < {left_operand}"

  TRIMA:
    type: trend
    scale_type: price_absolute
    thresholds: null
    conditions:
      long: "close > {left_operand}"
      short: "close < {left_operand}"

  MIDPOINT:
    type: trend
    scale_type: price_absolute
    thresholds: null
    conditions:
      long: "close > {left_operand}"
      short: "close < {left_operand}"

  MIDPRICE:
    type: trend
    scale_type: price_absolute
    thresholds: null
    conditions:
      long: "close > {left_operand}"
      short: "close < {left_operand}"

  BBANDS:
    type: volatility
    scale_type: price_absolute
    thresholds: null
    components: ["upper", "middle", "lower"]
    conditions:
      long: "close < {left_operand}_lower"
      short: "close > {left_operand}_upper"

  LINEARREG:
    type: statistics
    scale_type: price_absolute
    thresholds: null
    conditions:
      long: "close > {left_operand}"
      short: "close < {left_operand}"

  TSF:
    type: statistics
    scale_type: price_absolute
    thresholds: null
    conditions:
      long: "close > {left_operand}"
      short: "close < {left_operand}"

  # パターン認識系指標
  CDL_DOJI:
    type: pattern_recognition
    scale_type: oscillator_plus_minus_100
    thresholds: null
    conditions:
      long: "{left_operand} != 0"
      short: "{left_operand} != 0"

  CDL_HAMMER:
    type: pattern_recognition
    scale_type: oscillator_plus_minus_100
    thresholds: null
    conditions:
      long: "{left_operand} > 0"
      short: null  # ハンマーはロングのみ

  CDL_HANGING_MAN:
    type: pattern_recognition
    scale_type: oscillator_plus_minus_100
    thresholds: null
    conditions:
      long: null  # ハンギングマンはショートのみ
      short: "{left_operand} < 0"

  CDL_PIERCING:
    type: pattern_recognition
    scale_type: oscillator_plus_minus_100
    thresholds: null
    conditions:
      long: "{left_operand} > 0"
      short: null

  CDL_DARK_CLOUD_COVER:
    type: pattern_recognition
    scale_type: oscillator_plus_minus_100
    thresholds: null
    conditions:
      long: null
      short: "{left_operand} < 0"

  CDL_THREE_WHITE_SOLDIERS:
    type: pattern_recognition
    scale_type: oscillator_plus_minus_100
    thresholds: null
    conditions:
      long: "{left_operand} > 0"
      short: null

  CDL_THREE_BLACK_CROWS:
    type: pattern_recognition
    scale_type: oscillator_plus_minus_100
    thresholds: null
    conditions:
      long: null
      short: "{left_operand} < 0"

  # 統計系指標
  CORREL:
    type: statistics
    scale_type: oscillator_plus_minus_100
    thresholds:
      all:
        pos_threshold: 0.3
        neg_threshold: -0.7
    conditions:
      long: "{left_operand} > {pos_threshold}"
      short: "{left_operand} < {neg_threshold}"

  LINEARREG_ANGLE:
    type: statistics
    scale_type: oscillator_plus_minus_100
    thresholds:
      all:
        long_lt: 45
        short_gt: -45
    conditions:
      long: "{left_operand} > {threshold}"
      short: "{left_operand} < {threshold}"

  LINEARREG_SLOPE:
    type: statistics
    scale_type: momentum_zero_centered
    thresholds:
      all:
        long_gt: 0
        short_lt: 0
    conditions:
      long: "{left_operand} > {threshold}"
      short: "{left_operand} < {threshold}"

# スケールタイプ定義
scale_types:
  oscillator_0_100:
    range: [0, 100]
  oscillator_plus_minus_100:
    range: [-100, 100]
  momentum_zero_centered:
    range: null
  price_absolute:
    range: null

# デフォルト閾値マッピング
default_thresholds:
  oscillator_0_100:
    aggressive:
      long_lt: 48
    conservative:
      long_lt: 52
    normal:
      long_lt: 50
  oscillator_plus_minus_100:
    aggressive:
      long_gt: -2
    conservative:
      long_gt: 2
    normal:
      long_gt: 0
  momentum_zero_centered:
    aggressive:
      long_gt: -0.1
    conservative:
      long_gt: 0.1
    normal:
      long_gt: 0.0