"""
Pandas-TA設定管理

PANDAS_TA_CONFIG と関連定数を分離した独立モジュール
"""

# pandas-ta動的処理設定
PANDAS_TA_CONFIG = {
    "RSI": {
        "function": "rsi",
        "params": {"length": ["length", "period"]},
        "data_column": "Close",
        "returns": "single",
        "default_values": {"length": 14},
    },
    "SMA": {
        "function": "sma",
        "params": {"length": ["length", "period"]},
        "data_column": "Close",
        "returns": "single",
        "default_values": {"length": 20},
    },
    "EMA": {
        "function": "ema",
        "params": {"length": ["length", "period"]},
        "data_column": "Close",
        "returns": "single",
        "default_values": {"length": 20},
    },
    "WMA": {
        "function": "wma",
        "params": {"length": ["length", "period"]},
        "data_column": "Close",
        "returns": "single",
        "default_values": {"length": 20},
    },
    "MACD": {
        "function": "macd",
        "params": {"fast": ["fast"], "slow": ["slow"], "signal": ["signal"]},
        "data_column": "Close",
        "returns": "multiple",
        "return_cols": ["MACD", "Signal", "Histogram"],
        "default_values": {"fast": 12, "slow": 26, "signal": 9},
    },
    "SUPERTREND": {
        "function": "supertrend",
        "params": {"length": ["length"], "multiplier": ["multiplier", "factor"]},
        "data_column": "open_high_low_close",
        "returns": "complex",
        "return_cols": ["ST", "D"],
        "default_values": {"length": 10, "multiplier": 3.0},
    },
    "UI": {
        "function": "ui",
        "params": {"length": ["length"]},
        "data_column": "Close",
        "returns": "single",
        "default_values": {"length": 14},
    },
    "SINWMA": {
        "function": "sinwma",
        "params": {"length": ["length"]},
        "data_column": "Close",
        "returns": "single",
        "default_values": {"length": 14},
    },
    "PPO": {
        "function": "ppo",
        "params": {"fast": ["fast"], "slow": ["slow"], "signal": ["signal"]},
        "data_column": "Close",
        "returns": "multiple",
        "return_cols": ["PPO_0", "PPO_1", "PPO_2"],
        "default_values": {"fast": 12, "slow": 26, "signal": 9},
    },
        "EMA": {
        "function": "ema",
        "params": {"length": ["length"]},
        "data_column": "Close",
        "returns": "single",
        "default_values": {"length": 20},
    },
    "TEMA": {
        "function": "tema",
        "params": {"length": ["length"]},
        "data_column": "Close",
        "returns": "single",
        "default_values": {"length": 14},
    },
    "ALMA": {
        "function": "alma",
        "params": {"length": ["length"], "sigma": ["sigma"], "offset": ["offset"]},
        "data_column": "Close",
        "returns": "single",
        "default_values": {"length": 9, "sigma": 6.0, "offset": 0.85},
    },
    "FWMA": {
        "function": "fwma",
        "params": {"length": ["length"]},
        "data_column": "Close",
        "returns": "single",
        "default_values": {"length": 10},
    },
    "STOCHRSI": {
        "function": "stochrsi",
        "params": {"length": ["length", "period"], "k_period": ["k_period"], "d_period": ["d_period"]},
        "data_column": "Close",
        "returns": "multiple",
        "default_values": {"length": 14, "k_period": 5, "d_period": 3},
    },
    "KST": {
        "function": "kst",
        "params": {
            "roc1": ["roc1", "r1", "rorc1"],
            "roc2": ["roc2", "r2", "rorc2"],
            "roc3": ["roc3", "r3", "rorc3"],
            "roc4": ["roc4", "r4", "rorc4"],
            "sma1": ["sma1", "n1", "length"],
            "sma2": ["sma2", "n2"],
            "sma3": ["sma3", "n3"],
            "sma4": ["sma4", "n4"],
            "signal": ["signal"]
        },
        "data_column": "Close",
        "returns": "multiple",
        "return_cols": ["KST", "KST_Signal"],
        "default_values": {"roc1": 10, "roc2": 15, "roc3": 20, "roc4": 30, "sma1": 10, "sma2": 10, "sma3": 10, "sma4": 15, "signal": 9},
    },
    "BBANDS": {
        "function": "bbands",
        "params": {"length": ["length", "period"], "std": ["std", "multiplier"]},
        "data_column": "Close",
        "returns": "multiple",
        "return_cols": ["BBL", "BBM", "BBU"],
        "default_values": {"length": 20, "std": 2.0},
    },
    "AO": {
        "function": "ao",
        "params": {},
        "multi_column": True,
        "data_columns": ["High", "Low"],
        "returns": "single",
        "default_values": {},
    },
    "RVI": {
        "function": "rvi",
        "params": {"length": ["length", "period"]},
        "data_column": "Close",
        "returns": "single",
        "default_values": {"length": 14},
    },
    "UO": {
        "function": "uo",
        "params": {"fast": ["fast"], "medium": ["medium"], "slow": ["slow"]},
        "data_column": "ohlc",
        "returns": "single",
        "default_values": {"fast": 7, "medium": 14, "slow": 28},
    },
    "AROON": {
        "function": "aroon",
        "params": {"length": ["length", "period"]},
        "data_column": "open_high_low",  # 高値と安値のみを使用
        "returns": "multiple",
        "return_cols": ["AROONU", "AROOND"],
        "default_values": {"length": 14},
    },
    "LINREG_SLOPE": {
        "function": "linearreg_slope",
        "params": {"length": ["length", "timeperiod"]},
        "data_column": "Close",
        "returns": "single",
        "default_values": {"length": 14},
    },
    "T3": {
        "function": "t3",
        "params": {"length": ["length", "period"], "a": ["a", "vfactor"]},
        "data_column": "Close",
        "returns": "single",
        "default_values": {"length": 5, "a": 0.7},
    },
    "KVO": {
        "function": "kvo",
        "params": {"fast": ["fast"], "slow": ["slow"]},
        "multi_column": True,
        "data_columns": ["High", "Low", "Close", "Volume"],
        "returns": "multiple",
        "return_cols": ["KVO_34_55_13", "KVOs_34_55_13"],
        "default_values": {"fast": 34, "slow": 55},
    },
}

POSITIONAL_DATA_FUNCTIONS = {
    "rsi",
    "wma",
    "sar",
    "roc",
    "stoch",
    "bbands",
    "macd",
    "dpo",
    "rmi",
    "kama",
    "trima",
    "wma",
    "ma",
    "midpoint",
    "midprice",
    "ht_trendline",
    "adosc",
    "correl",
    "linearreg",
    "stddev",
    "tsf",
    "var",
    "linearreg_angle",
    "linearreg_intercept",
    "linearreg_slope",
    "hma",
    "zlma",
    "swma",
    "alma",
    "rma",
    "tsi",
    "pvo",
    "cfo",
    "cti",
    "sma_slope",
    "price_ema_ratio",
    "beta",
    "belta",
    "qqe",
    "smi",
    "trix",
    "apo",
    "WMA",
    "TRIMA",
    "MA",
    "chop",
    "vortex",
    "BBANDS",
    "hilo",
    "ad",
    "eom",
    "kvo",
    "cmf",
}